<div class="container-fluid">
    <h1 class="page-header">Pedidos</h1>
    
    <div class="row">

<!--<div class="row">
	
		<div class="well form-inline col-xs-12 col-md-12  form_agregar_detalle">

        
        <div class="form-group col-sm-3">
            <select id="productos" name="productos" class="form-control ">
                <option value="">--Productos--</option>
                <?php foreach ($this->productos as $producto): ?>
                <option value="<?php echo $producto->id; ?>" <?php echo (isset($this->params['f_grado']) && $this->params['f_grado'] == $grado->id) ? 'selected' : ''; ?>><?php echo utf8_encode($producto->descripcion); ?></option>
                <?php endforeach; ?>
            </select>
        </div>

            <div class="form-group col-sm-3">
                <input type="text" name="serial" id="serial" value="" class="form-control col-sm-2" placeholder="Serial">
            </div>

            <div class="form-group col-sm-2">
                <input type="text" name="nota" id="nota" value="" class="form-control col-sm-2" placeholder="Nota">
            </div>
            <div class="form-group col-sm-2">
                <input type="text" name="cantidad" id="cantidad" value="1" class="form-control col-sm-2"  placeholder="Cantidad">
            </div>
            <input type="hidden" name="id_pedido" id="id_pedido" value="<?php echo $this->id; ?>" class="form-control col-sm-2">



        <div class="form-group col-sm-2">
            <a id="btn-agregar_detalle" data-url="<?php echo $this->baseUrl('ajax/detalle'); ?>" class="btn btn-default"><span class="glyphicon glyphicon-plus"></span> Agregar</a>
            
        </div>
        
		</div>
	
	</div>-->


            <!--++++++++++++++++++++ Comienzo del formulario ++++++++++++++++++-->
<div class="row">

<?php $total_general=0; ?>
<table class="table table-hover table-striped" id="tb_estudiantes2">
        <thead style=""><tr>
            <th>Id</th>
             <th >Descripcion</th>
            <th>Cantidad</th>
            <th class="hidden-xs">precio </th>
            <th>Total </th>
            
            
        </tr></thead><tbody id="tbody_detalle">
        <?php foreach ($this->detalles as $row): $total_general=$total_general+$row->total;?>
		
		

            <tr id="<?php echo $row->id; ?>">
                <td><?php echo $row->id; ?></td>
                <td ><?php echo $row->descripcion; ?>


                

               


                </td>
                <td><?php echo $row->cantidad; ?></td>
                <td class="hidden-xs"><?php echo $row->precio; ?></td>

                <td> <span class="total"> <?php echo $row->total; ?></span> </td>
               
                
            </tr>
        <?php endforeach; ?>
		</tbody>
        <tfoot>
            <tr>
                <td id="ultima_fila" colspan="7">Total de Pedido:<span class="total_general"> <?php echo $total_general; ?> </span> </td>
            </tr>
        </tfoot>
	</table>

</div>


 <div class="row">
     <a name="btn_cancel" href="wake/pedidos" id="btn_cancel" type="button" class="btn btn-danger">Volver</a>
 </div>      





    </div>
    
</div>




