<section class="page-crumb">
    <div class="container">
        <!-- Page Heading/Breadcrumbs -->
        <div class="row">
            <div class="col-lg-12">
        <ol class="breadcrumb">
                    <li><a href="<?php echo $this->baseUrl('/'); ?>">Home</a>
                    </li>
                    <li><a href="<?php echo $this->baseUrl('/solicitud'); ?>">Solicitudes</a>
                    </li>
                    <li class="active">Validar</li>
                </ol>
            </div>
        </div>
        <!-- /.row -->
  </div>
</section>


<section class="service-w3ls">
  <h3 class="text-center w3layouts w3 w3l w3ls agileits-w3layouts agile w3-agile">Solicitud de Validacion de Informe</h3>
  <p class="text-center w3layouts w3 w3l w3ls agileits-w3layouts agile w3-agile">Formulario de Solicitud de Validacion de Informe.</p> 
  <div class="container"> 
        <!-- Service Panels -->
        <div class="row">

        <div class="col-sm-3"></div>
        <div class="col-sm-6">

        <form id="form_validador" name="form_validador" enctype="multipart/form-data" action="<?php echo $this->baseUrl('/solicitud/validador'); ?>" method="post"><div>

    <input type="hidden" id="id" name="id"  value="<?php echo time();?>">

    <div class="form-group">
      <label for="cedula" class="required">Número de Informe DPT *</label>
      <input type="text"  name="dpt" id="dpt" value="" class="form-control" placeholder="">
    </div>

    <div class="form-group">
      <label for="cedula" class="required">Código de Validación Tirex CVT *</label>
      <input type="text"  name="cvt" id="cvt" value="" class="form-control" placeholder="">
    </div>


    <div class="form-group">
      <label for="cedula" class="required">Email *</label>
      <input type="text"  name="email" id="email" value="" class="form-control" placeholder="Correo Electronico">
    </div>



    <dt id="buttons-label">&#160;</dt>
    <dd id="buttons-element">
      <fieldset id="fieldset-buttons">
        <dl>
          <input type="submit" name="btn_submit" id="btn_submit" value="Guardar" class="btn btn-default">

          <button name="btn_cancel" id="btn_cancel" type="button" class="btn btn-danger">Cancelar</button>
        </dl>

      </fieldset>
    </dd>
    </div>
  </form> 

  </div><!--  fin col-sm-6 -->





    </div>  
  </div>
</section>  

<section class="service-agile">
  <div class="container">
    <h3 class="text-center agileits agileinfo wthree w3-agileits">Avaluos</h3>
    <p class="text-center agileits agileinfo wthree w3-agileits">Un avalúo es la estimación del valor de un bien mueble o inmueble expresado en cifras monetarias de acuerdo a criterios, herramientas y a metodologías científicas adecuadas tomando en cuenta las condiciones físicas, características, ubicación, uso, conservación, mantenimiento, operatividad, funcionamiento, y de una indagación y análisis de mercado, para la fecha en que se realiza dicha estimación.  .</p> 
        <!-- Service Tabs -->
        <div class="row">
            <div class="col-lg-12">
                <ul id="myTab" class="nav nav-tabs nav-justified">
                    <?php $j=0; ?>
                    <?php foreach ($this->avaluos as $ava): ?>

                      <?php if ( $j!=0): ?>
                        <li class=""><a href="#service-<?php echo $ava->id; ?>" data-toggle="tab"> <?php echo $ava->titulo; ?></a>
                        </li>
                        <?php $j++; ?>
                      <?php endif ?>

                      <?php if ($j==0): ?>
                        <li class="active"><a href="#service-<?php echo $ava->id; ?>" data-toggle="tab"> <?php echo $ava->titulo; ?></a>
                        </li>
                        <?php $j++; ?>
                      <?php endif ?>
                       
                    <?php endforeach ?>

                    
                </ul>

                <div id="myTabContent" class="tab-content">
                    
                    <?php $j=0; ?>
                    <?php foreach ($this->avaluos as $ava): ?>

                      <?php if ( $j!=0): ?>

                      <div class="tab-pane fade" id="service-<?php echo $ava->id; ?>">
                        <h4><?php echo $ava->titulo; ?></h4>
                        <img class="img " alt="<?php echo $ava->titulo; ?>" title="<?php echo $ava->titulo; ?>" src="<?php echo $this->baseUrl($ava->imagen); ?>">
                        <?php echo $ava->descripcion; ?>
                    </div>

                        
                        <?php $j++; ?>
                      <?php endif ?>

                      <?php if ($j==0): ?>

                      <div class="tab-pane fade active in" id="service-<?php echo $ava->id; ?>">
                      
                        <h4><?php echo $ava->titulo; ?></h4>
                        <img class="img " alt="<?php echo $ava->titulo; ?>" title="<?php echo $ava->titulo; ?>" src="<?php echo $this->baseUrl($ava->imagen); ?>">
                        <?php echo $ava->descripcion; ?>
                        
                    </div>


                        
                        <?php $j++; ?>
                      <?php endif ?>
                       
                    <?php endforeach ?>



                   
                    
            </div>
        </div>
        <hr>
  </div>  
</section>  
