<div class="container">
    <h1 class="page-header">Registro de Certificaciones</h1>
    <div style="position: absolute; z-index: 9999; <?php echo ($this->auth->getIdentity()->role === 'administrador') ? 'display:block;' : 'display:none;'; ?>">
    </div>
    <div class="row">


 <form id="form_asignado" name="form_asignado" enctype="application/x-www-form-urlencoded" method="post" action=""><div>

 <div class="form-group"><label for="codigo" class="required">Código de Certificación</label>

<input type="text" name="codigo" id="codigo" value="" class="form-control" placeholder="Código de Certificación"></div>

 
 <div class="form-group"><label for="estudiante" class="required">Estudiante</label>

<div class="col-xs-12 input-group parent-search">
         <input type="text" id="estudiante" name="estudiante" class="form-control" onkeypress="return isNumberKey(event);"  placeholder="ej: 12345678" required="">
          <div class="input-group-btn">
          <button id="btn_buscar_es" class="btn btn-default" type="button">Buscar</button>
           </div>
    </div>



<!--<input type="text" name="estudiante" id="estudiante" value="" class="form-control"></div>-->

<div id="resultado">	</div>
<div class="form-group"><label for="curso" class="required">Curso</label>

<select name="curso" id="curso" class="form-control">

     <option value="">--Curso--</option>
                    <?php foreach ($this->cursos as $curso): ?>
                    <option value="<?php echo $curso->id; ?>" ><?php echo utf8_encode($curso->descripcion); ?></option>
                    <?php endforeach; ?>



</select></div>
<div class="form-group"><label for="fecha_cap" class="required">Fecha de Certificación</label>

<input type="text" name="fecha_cap" id="fecha_cap" value="" class="form-control fecha" placeholder="Fecha de Certificación"></div>

<div class="form-group"><label for="fecha_ven" class="required">Fecha de Vencimiento</label>

<input type="text" name="fecha_ven" id="fecha_ven" value="" class="form-control fecha" placeholder="Fecha de Vencimiento"></div>
<dt id="buttons-label">&#160;</dt><dd id="buttons-element"><fieldset id="fieldset-buttons"><dl>

<input type="submit" name="btn_submit" id="btn_submit" value="Guardar" class="btn btn-default">

<button name="btn_cancel_cert" id="btn_cancel_cert" type="button" class="btn btn-danger">Cancelar</button></dl></fieldset></dd></div></form> 





    </div>
    
</div>
