<!DOCTYPE html PUBLIC "-//W3C//DTD HTML 4.01 Transitional//EN">
<html>
    <head>
        <meta charset="utf-8">
        <title>Detalles de Registro</title>
    </head>

 
    <body>

    <?php $i=0; foreach ($this->asignado as $asignado): $i++;  
  
            $fecha_cap=$asignado->fecha_cap;  
            $fecha_ven=$asignado->fecha_ven; 
            $codigo=$asignado->codigo2; 
            $id_estudiante=$asignado->id_estudiante;
     endforeach; 

     $estudiante=$this->ObjMembers->fetchAll('id='.$id_estudiante);

     $i=0; foreach ($estudiante as $estudiante): $i++;  
  
            $nombre=utf8_encode(ucwords($estudiante->nombre));  
            $apellido=utf8_encode(ucwords($estudiante->apellido)); 
        
     endforeach; 

     ?>  
	<table border="0">
		<tr>
			<td>&nbsp;</td>
		</tr>
		<tr>
			<td><table><tr><td  width="90%" align="right"><strong style="font-size:20px; color:red;" ><?php echo strtoupper ($codigo); ?></strong></td><td width="10%">&nbsp;</td></tr></table></td>
		</tr>
		<tr>
			<td style="height:170px;">&nbsp;</td>
		</tr>
		<tr>
			<td style="font-size:30px" align="center"><strong><?php echo $nombre.' '.$apellido; ?></strong></td>
		</tr>
		<tr>
			<td style="height:90px;">&nbsp;</td>
		</tr>
		<tr>
			<td style="font-size:14px" align="center">Fecha de Certificación:<?php echo $fecha_cap; ?> - 
            Fecha de Vencimiento: <?php echo $fecha_ven; ?></td>
		</tr>
	</table>
       


    </body>
</html>