<!DOCTYPE html PUBLIC "-//W3C//DTD HTML 4.01 Transitional//EN">
<html>
    <head>
        <meta charset="utf-8">
        <title>Reporte</title>
        <style>
            body {font-size: 11px;}
        </style>
    </head>
    <body>
        <h2>Reporte de Certificados</h2>
        <table cellpadding="0" cellspacing="0" border="0">
            <tr>
                <td>
                    <strong>Curso:</strong>
                    <?php if (isset($this->params['f_curso']) && !empty($this->params['f_curso'])): ?>
                        <?php echo $this->objCursos->getCursoInfo($this->params['f_curso']); ?>
                    <?php endif; ?>
                </td>
                <td>
                    <strong>Ciudad:</strong>
                    <?php if (isset($this->params['f_city']) && !empty($this->params['f_city'])): ?>
                         <?php echo $this->objCities->getCity($this->params['f_city']); ?>
                    <?php endif; ?>
                </td>
            </tr>
            <tr>
              <td>
                    <strong>Estado:</strong>
                    <?php if (isset($this->params['f_state']) && !empty($this->params['f_state'])): ?>
                         <?php echo $this->objStates->getState($this->params['f_state']); ?>
                    <?php endif; ?>
                </td>
              <td>
                    <strong>Status:</strong>
                    <?php if (isset($this->params['f_status']) && !empty($this->params['f_status'])): ?>
                         <?php  if($this->params['f_status']=='1'){echo "Vigente";}else{echo "Vencido";} ?>
                    <?php endif; ?>
                </td>
            </tr>
        </table>
        <table cellpadding="2" cellspacing="2" border="0">
            <tr style="font-size:10px; background-color: #BDBDBD; font-weight: bold; color: white; text-align: center;">
                <th width="6%" height="30px" style="border-right: 1px solid #ccc;">Cédula</th>
				<th width="6%" height="30px" style="border-right: 1px solid #ccc;">Codigo</th>
				<th width="19%" height="30px" style="border-right: 1px solid #ccc;">Nombre y Apellido</th>
				<th width="9%" height="30px" style="border-right: 1px solid #ccc;">Telefono</th>
				<th width="10%" height="30px" style="border-right: 1px solid #ccc;">Ciudad</th>
				<th width="9%" height="30px" style="border-right: 1px solid #ccc;">Fecha de<br> Nacimiento</th>
                <th width="16%" height="30px" style="border-right: 1px solid #ccc;">Curso</th>
                <th width="9%" height="30px" style="border-right: 1px solid #ccc;">Fecha <br>Certificación</th>
                <th width="9%" height="30px" style="border-right: 1px solid #ccc;">Fecha<br> Vencimiento</th>
                <th width="6%" height="30px" style="border-right: 1px solid #ccc;">Status</th>
            </tr>
            <?php $i=0; foreach ($this->members as $row): $i++; ?>
                <tr style="font-size:8px; background-color: <?php echo ($i%2==0) ? '#eee;' : '#fff'; ?>;">
                     <td height="30px" style="border-right: 1px solid #ccc;"><?php echo $row->cedula; ?></td>
					<td height="30px" style="border-right: 1px solid #ccc;"><?php echo $row->codigo; ?></td>
                    <td height="30px" style="border-right: 1px solid #ccc;"><?php echo utf8_encode(ucwords($row->nombre.' '.$row->apellido)); ?></td>
					<td height="30px" style="border-right: 1px solid #ccc;"><?php echo $row->tlf; ?></td>
					<td height="30px" style="border-right: 1px solid #ccc;"><?php echo utf8_encode(ucwords($this->objCities->getCity($row->ciudad))); ?></td>
					<td height="30px" style="border-right: 1px solid #ccc;"><?php echo $row->fecha_nac; ?></td>
                    <td height="30px" style="border-right: 1px solid #ccc;"><?php echo utf8_encode(ucwords($row->descripcion)); ?></td>
                    <td height="30px" style="border-right: 1px solid #ccc;"><?php echo $row->fecha_cap; ?></td>
                    <td height="30px" style="border-right: 1px solid #ccc;"><?php echo $row->fecha_ven; ?></td>
                     <td height="30px" style="border-right: 1px solid #ccc;"><?php  if($row->status==1){echo "Vigente";}else{echo "Vencido";} ?></td>
                </tr>
            <?php endforeach; ?>
        </table>
    </body>
</html>