
  <!--contact-->

  <div class="container" style="margin: 0px; padding: 0px;  width: 100%; height: auto;">
  
    <iframe src="https://www.google.com/maps/embed?pb=!1m16!1m12!1m3!1d4665.188250955415!2d-66.8997328109211!3d10.505386085090327!2m3!1f0!2f0!3f0!3m2!1i1024!2i768!4f13.1!2m1!1surb+san+bernardino%2C+av.+vollmer%2C+edif+vollmer.+caracas+venezuela!5e0!3m2!1ses!2sve!4v1491303863727" frameborder="0" style="border:0; width:100%; height: 15em; " allowfullscreen></iframe>
  </div>
  <br>

  <div class="container">
    <div class="row">
      <div class="col-sm-12">
        <h1>Contáctanos</h1>
      </div>
      

      <div class="col-sm-6">
        <div class="col-sm-12">
          <h3 class="page-header tittle_detalle"> Formulario de Contacto</h3>
        </div>

        <form>
          <div class="form-group col-sm-12">
            <label for="cedula" class="required">Nombre *</label>
            <input class="form-control" type="text" id="nombre"  name="nombre" placeholder="Nombre" required="">
          </div>

          <div class="form-group col-sm-12">
            <label for="cedula" class="required">Email *</label>
              <input class="form-control" type="mail" id="email" name="email" placeholder="Email" required="">
            
          </div>

          <div class="form-group col-sm-12">
            <label for="cedula" class="required">Telefono *</label>
            <input class="form-control" type="text" id="telefono" name="telefono" placeholder="Telefono" required="">
          </div>

          <div class="form-group col-sm-12">
            <label for="cedula" class="required">Mensaje *</label>
            <textarea class="form-control" id="mensaje" name="mensaje"  placeholder="Mensaje" required=""></textarea>
          </div>

          <div class="respuesta"></div>

          

          <input type="button" class="btn btn-primary" onclick="correo();" value="Enviar" >
          
          <input type="button" class="btn btn-default" value="Limpiar" >
        </form>








      </div>
      <div class="col-sm-6">
        <div class="col-sm-12">
          <h3 class="page-header tittle_detalle"> Informacion de Contacto</h3>
        </div>

        <div class="col-sm-12 contacto_info">
          
          <p><span class="glyphicon glyphicon-map-marker" aria-hidden="true"></span> Venezuela y Republica Domincana</p>
          <p><a href="mailto:contact@example.com"><span class="glyphicon glyphicon-envelope" aria-hidden="true"></span> contacto@encasaplus.com</a></p>
          <p><span class="glyphicon glyphicon-earphone" aria-hidden="true"></span>+58 424 123-1234</p>
          <p><span class="glyphicon glyphicon-earphone" aria-hidden="true"></span>+58 426 123-1234</p>
          <p><span class="glyphicon glyphicon-earphone" aria-hidden="true"></span>+58 412 123-1234</p>
          <!--<p><span class="glyphicon glyphicon-map-marker" aria-hidden="true"></span>Distrito Capital Caracas.  Urb San Bernardino, Av. Vollmer, Edif. Vollmer Piso 1 Oficina 41</p>-->
        </div>
        


      </div>
    </div>
  </div>

  <br><br>


