           <!--popular-->

<div class="featured-section" id="projects">
  <div class="container">
        
       
        <h2 class="tittle"> Nuestros Asesores </h2>
         <div class="content-bottom-in">

      

        <?php foreach ($this->elementos as $asesor): ?>
           

          <div class="col-md-4 col-sm-4 col-xs-6 propiedades" style="margin-bottom: 1em;">
          <div class="project-fur">
                <a href="<?php echo $this->baseUrl('/sitio/ver/empresa/').$asesor->id; ?>"  ><img class="img-responsive" src="<?php echo $this->baseUrl('/assets/img/').$asesor->imagen; ?>" alt="" />  </a>
                  <div class="fur">
                    <div class="fur1" >
                                        <span class="fur-money"><?php echo $asesor->name.' '.$asesor->lastname; ?> </span>
                                      
                                        <span ><small>Ubicacion: <?php  echo $asesor->state ?> </small></span>
                                    </div>
                                  <div class="fur2" style="    padding: 12px 5px 0px 5px;   text-align: center;">
                                      <h6 class="fur-name"><a href="<?php echo $this->baseUrl('/sitio/ver/empresa/').$asesor->id; ?>" >Ver Propiedades</a></h6>
                                   </div>
                  </div>  
                              
              </div>
            </div>

          
        <?php endforeach ?>

        
          <div class="clearfix"></div>
        </div>
      </div>
    </div>
    <!--popular-->
