
  <div class="content">
    <div class="serach-w3agile">
      <div class="container">
        <h3 class="tittle">Buscar Propiedades</h3>
        <div class="place-grids">
         

 
   
       
          <div class="clearfix"></div>
          <br>


          <input class="filtros" type="hidden" name="f_estado" id="f_estado">
          <input class="filtros" type="hidden" name="f_ciudad" id="f_ciudad">
          <input class="filtros" type="hidden" name="f_municipio" id="f_municipio">
          <input  class="filtros" type="hidden" name="f_parroquia" id="f_parroquia">
        




          <div class="row">
  <div class="col-lg-8 col-lg-offset-2">

      <select id="tipo_propiedad" name="tipo_propiedad" class=" col-sm-3 selectpicker form-control input-lg" data-live-search="true" title="Tipos de Propiedades">
                        <option value="Apartamento">Apartamento</option>
                        <option value="Casa">Casa</option>
                        <option value="Local Comercial">Local Comercial</option>
                        <option value="Galpon">Galpon</option>
                        <option value="Residencia">Residencia</option>
                    </select>

      <div class="input-group input-group-lg">
      <input type="text"  id="buscador" name="buscador" class="col-sm-9 form-control" placeholder="Buscar Propiedades">
      <span class="input-group-btn">
        <button id="btn_buscar" name="btn_buscar" onclick="buscar()" class="btn btn-default" type="button"><span class="glyphicon glyphicon-search" aria-hidden="true"></span></button>
      </span>
    </div>





  </div><!-- /.col-lg-6 -->
  </div><!-- /.row -->











        </div>
      </div>
    </div>
    
    <!--popular-->
    <!--high properties-->
     
    <!--high properties-->
    <!--featured-->
    
    <!--featured-->





    <!--Projects
    <div class="content">
      <div class="projects-agile">
        <div class="container">
          <h2 class="tittle">Nuestras Propiedades</h2>
            <div class="portfolio_grid_w3lss">
              <div class="col-md-4 w3agile_Projects_grid">
                <div class="w3agile_Projects_image">
                  <a class="sb" href="images/apa1.jpg" title="Conjunto Residencial Le Mirage Urb Los Campitos - Caracas">
                    <figure>
                      <img src="images/apa1.jpg" alt="" class="img-responsive" />
                      <figcaption>
                        <h4>Conjunto Residencial Le Mirage Urb Los Campitos</h4>
                        <p>
                          Exclusivo Proyecto, ubicado en la Calle A de la urbanización Mirador de Los Campitos, Municipio Baruta del Estado Miranda, Área Metropolitana de Caracas
                        </p>
                      </figcaption>
                    </figure>
                  </a>
                </div>
              </div>
              <div class="col-md-4 w3agile_Projects_grid">
                <div class="w3agile_Projects_image">
                  <a class="sb" href="images/3.jpg" title="quis nostrud exercitation ullamco laboris quis autem vel eum iure reprehenderit qui in ea voluptate velit esse quam nihil molestiae consequatur, vel illum qui dolorem eum">
                    <figure>
                      <img src="images/3.jpg" alt="" class="img-responsive" />
                      <figcaption>
                        <h4>Loft Cayena</h4>
                        <p>
                          Residencia con 10 exclusivos apartamentos a estrenar en Calle Ciega con Vigilancia Privada.
                        </p>
                      </figcaption>
                    </figure>
                  </a>
                </div>
              </div>
              <div class="col-md-4 w3agile_Projects_grid">
                <div class="w3agile_Projects_image">
                  <a class="sb" href="images/2.jpg" title="quis nostrud exercitation ullamco laboris quis autem vel eum iure reprehenderit qui in ea voluptate velit esse quam nihil molestiae consequatur, vel illum qui dolorem eum">
                    <figure>
                      <img src="images/2.jpg" alt="" class="img-responsive" />
                      <figcaption>
                        <h4>Altos de Suritaima</h4>
                        <p>
                          Altos de Suritaima, complejo residencial con vigilancia privada, áreas verdes y clima de montaña.
                        </p>
                      </figcaption>
                    </figure>
                  </a>
                </div>
              </div>
              <div class="clearfix"> </div>
            </div>
            <div class="portfolio_grid_w3lss">
              <div class="col-md-4 w3agile_Projects_grid">
                <div class="w3agile_Projects_image">
                  <a class="sb" href="images/apa2.jpg" title="quis nostrud exercitation ullamco laboris quis autem vel eum iure reprehenderit qui in ea voluptate velit esse quam nihil molestiae consequatur, vel illum qui dolorem eum">
                    <figure>
                      <img src="images/apa2.jpg" alt="" class="img-responsive" />
                      <figcaption>
                        <h4> Apartamento en Guaicay</h4>
                        <p>
                          Bello apartamento con un gran potencial, excelente iluminacion y ventilacion.
                        </p>
                      </figcaption>
                    </figure>
                  </a>
                </div>
              </div>
              <div class="col-md-4 w3agile_Projects_grid">
                <div class="w3agile_Projects_image">
                  <a class="sb" href="images/apa4.jpg" title="quis nostrud exercitation ullamco laboris quis autem vel eum iure reprehenderit qui in ea voluptate velit esse quam nihil molestiae consequatur, vel illum qui dolorem eum">
                    <figure>
                      <img src="images/apa4.jpg" alt="" class="img-responsive" />
                      <figcaption>
                        <h4> Apartamento en Venta en El Rosal</h4>
                        <p>
                          Apartamento ideal ejecutivos de Alto nivel, Ubicado en edificio residencial de Estructura moderna.
                        </p>
                      </figcaption>
                    </figure>
                  </a>
                </div>
              </div>
              <div class="col-md-4 w3agile_Projects_grid">
                <div class="w3agile_Projects_image">
                  <a class="sb" href="images/apa5.jpg" title="quis nostrud exercitation ullamco laboris quis autem vel eum iure reprehenderit qui in ea voluptate velit esse quam nihil molestiae consequatur, vel illum qui dolorem eum">
                    <figure>
                      <img src="images/apa5.jpg" alt="" class="img-responsive" />
                      <figcaption>
                        <h4>Hermoso Apartamento en Venta</h4>
                        <p>Espectacular apartamento en Manzanares, completamente remodelado.
                        </p>
                      </figcaption>
                    </figure>
                  </a>
                </div>
              </div>
              <div class="clearfix"> </div>
            </div>
            <div class="portfolio_grid_w3lss">
              <div class="col-md-4 w3agile_Projects_grid">
                <div class="w3agile_Projects_image">
                  <a class="sb" href="images/apa6.jpg" title="quis nostrud exercitation ullamco laboris quis autem vel eum iure reprehenderit qui in ea voluptate velit esse quam nihil molestiae consequatur, vel illum qui dolorem eum">
                    <figure>
                      <img src="images/apa6.jpg" alt="" class="img-responsive" />
                      <figcaption>
                        <h4>Apartamento La Castellana</h4>
                        <p>
                          Excelente oportunidad de 160 m2 en La Castellana.
                        </p>
                      </figcaption>
                    </figure>
                  </a>
                </div>
              </div>
              <div class="col-md-4 w3agile_Projects_grid">
                <div class="w3agile_Projects_image">
                  <a class="sb" href="images/apa7.jpg" title="quis nostrud exercitation ullamco laboris quis autem vel eum iure reprehenderit qui in ea voluptate velit esse quam nihil molestiae consequatur, vel illum qui dolorem eum">
                    <figure>
                      <img src="images/apa7.jpg" alt="" class="img-responsive" />
                      <figcaption>
                        <h4>Los Samanes. Pb en Venta</h4>
                        <p>
                          Urbanización Los Samanes. Vendo preciosa PB de 200 m2 más 120 m2 de hermoso y verde jardín.
                        </p>
                      </figcaption>
                    </figure>
                  </a>
                </div>
              </div>
              <div class="col-md-4 w3agile_Projects_grid">
                <div class="w3agile_Projects_image">
                  <a class="sb" href="images/apa1.jpg" title="quis nostrud exercitation ullamco laboris quis autem vel eum iure reprehenderit qui in ea voluptate velit esse quam nihil molestiae consequatur, vel illum qui dolorem eum">
                    <figure>
                      <img src="images/apa1.jpg" alt="" class="img-responsive" />
                      <figcaption>
                        <h4>Apartamento en Lomas del Avila</h4>
                        <p>
                          Hermoso apartamento, iluminado y ventilado en urbanizacion cerrada con vigilancia 24 hrs.
                        </p>
                      </figcaption>
                    </figure>
                  </a>
                </div>
              </div>
              <div class="clearfix"> </div>
            </div>
          <script type="text/javascript" src="js/smoothbox.jquery2.js"></script>
        </div>
      </div>
    </div>
    <!--Projects-->









