
  <?php //$dolar=$this->identidad['dolar']; ?>
  <?php $dolar=1; ?>


  <div class=" header-right">
    <div class=" banner">
       <div class="slider">
          <div class="callbacks_container">
            <ul class="rslides" id="slider">  

              <?php foreach ($this->sliders as $slider): ?>
                 <li>
                   <div class="" style="background: url(<?php echo $this->baseUrl($slider->imagen); ?>) no-repeat;     width: 100%;    min-height: 550px;    background-size: cover;    -webkit-background-size: cover;">
                    <div class="caption">
                      <h3><span><?php echo $slider->titulo; ?></span></h3>
                      <p><?php echo $slider->descripcion; ?></p>
                    </div>
                  </div>
               </li>
              <?php endforeach ?>

   
            </ul>
        </div>
      </div>
    </div>
  </div>
   
  <!--header-bottom-->
  <div class="banner-bottom-top">
      <div class="container">
      <div class="bottom-header">
        <div class="header-bottom">
          <div class=" bottom-head">
            <a href="<?php echo $this->baseUrl('/inmuebles/buscar/tipo/apartamento'); ?>">
              <div class="buy-media">
                <i class="buy"> </i>
                <h6>Venta</h6>
              </div>
            </a>
          </div>
          <div class=" bottom-head">
            <a href="<?php echo $this->baseUrl('/inmuebles/buscar/tipo/apartamento'); ?>">
              <div class="buy-media">
              <i class="rent"> </i>
              <h6>Alquiler</h6>
              </div>
            </a>
          </div>
         
          
          
          <div class=" bottom-head">
            <a href="<?php echo $this->baseUrl('/asesores'); ?>">
              <div class="buy-media">
              <i class="deal"> </i>
              <h6>Comunidad</h6>
              </div>
            </a>
          </div>
          <div class="clearfix"> </div>
        </div>
      </div>
  </div>
  </div>
      <!--//-->
        
  <!--//header-bottom-->
  
  
<!--//header-->

<!--content-->
<!--div class="content">
  <div class="content-grid">
    <div class="container">
      <h3>Propiedades Populares</h3>



        <?php $ObjFotos = new Application_Model_DbTable_Fotos(); ?>
          <?php       $i=0; ?>
             <?php foreach ($this->destacados as $destacado): ?>
          <?php $foto=$ObjFotos->getsSolicitudUna($destacado->id);  ?>



        <div class="col-md-4 box_2" style="    margin-bottom: 2em;">
             <a href="<?php echo $this->baseUrl('/inmueble/ver/id/').$destacado->id; ?>"   class="mask">
                <img style="width: 100%;    height: 18em;" class="img-responsive zoom-img" src="<?php echo $this->baseUrl('/assets/images/300/').$foto->foto; ?>" alt="">
                <span class="four"><?php echo number_format($destacado->monto_vender*$dolar, 2, ',', '.'); ?> BS.</span>
             </a>
               <div class="most-1">
                 <h5><a href="<?php echo $this->baseUrl('/inmueble/ver/id/').$destacado->id; ?>"><?php echo substr($destacado->titulo, 0, 50); ?><?php if (strlen($destacado->titulo)>50){echo '...';} ?>
                   
                 </a></h5>
                  <p><?php echo $destacado->estado; ?></p>
               </div>
       </div>

        <?php   $i++; ?>

        <?php if ($i==3): $i=0; ?>
      <div class="clearfix"> </div>
        <?php endif ?>

          

         

          
        <?php endforeach ?>


       
      <div class="clearfix"> </div>
    </div>
  </div>
<!--service-->
  <div class="services">
    <div class="container">
      <div class="service-top">
        <h3>Servicios</h3>
        <p>Descripcion de los Servicios .</p>
      </div>
      
     <div class="services-grid">

          <?php foreach ($this->servicios as $servicio): ?>

              <div class="col-md-6 service-top1" style="margin-top: 1em;">
            <div class=" ser-grid"> 
              <img style="width: 6em;" class="img img-responsive" src="<?php echo  $this->baseUrl($servicio->imagen); ?>">   
            </div>
            <div  class="ser-top">
              <h4><?php   echo $servicio->titulo; ?></h4>
                <p><?php echo substr($servicio->descripcion, 0, 50); ?><?php if (strlen($servicio->descripcion)>50){echo '...';} ?></p>
            </div>
          <div class="clearfix"> </div>
          </div>

            
          <?php endforeach ?>

          
        
          <div class="clearfix"> </div>
      </div>
    </div>
  </div>
<!--//services-->
<!--features-->
    <div class="content-middle">
      <div class="container">
        <div class="mid-content">
          <h3><?php echo $this->nosotros['titulo']; ?></h3>
          <p><?php echo $this->nosotros['contenido']; ?></p>
          <a class="hvr-sweep-to-right more-in" href="<?php echo $this->baseUrl('/nosotros') ?>">Mas</a>
        </div>
      </div>
    </div>
<!--//features-->





  <!--div class="content">
    <div class="serach-w3agile">
      <div class="container" style=" position: absolute; top: 30em; z-index: 1000;">
        
        <div class="place-grids posi_buscador" >

          <div class="clearfix"></div>
          <br>


          <input class="filtros" type="hidden" name="f_estado" id="f_estado">
          <input class="filtros" type="hidden" name="f_ciudad" id="f_ciudad">
          <input class="filtros" type="hidden" name="f_zona" id="f_zona">
          

          <div class="row">
  <div class="col-lg-8 col-lg-offset-3 col-md-8 col-md-offset-3 col-sm-8 col-sm-offset-3 ">

      <select id="tipo_propiedad" name="tipo_propiedad" class=" col-sm-3 selectpicker form-control input-lg" data-live-search="true" title="Tipos de Propiedades">
                        <option value="">Todo</option>
                        <option value="Apartamento">Apartamento</option>
              <option value="Casa">Casa</option>
              <option value="Terreno">Terreno</option>
              <option value="Hacienda">Hacienda</option>
              <option value="Town House">Town House</option>
              <option value="Habitacion">Habitacion</option>
              <option value="Local Comercial">Local Comercial</option>
              <option value="Oficina Comercial">Oficina Comercial</option>
              <option value="Bodega-Galpon">Galpon</option>
              <option value="Fondo de Comercio">Fondo de Comercio</option>
              <option value="Hotel">Hotel</option>
              <option value="Edificio">Edificio</option>
              <option value="Anexo">Anexo</option>
                    </select>

      <div class="input-group input-group-lg">
      <input style="border-radius: 0px;" type="text"  id="buscador" name="buscador" class="col-sm-9 form-control" placeholder="Buscar Propiedades">
      <span class="input-group-btn">
        <button id="btn_buscar" name="btn_buscar" onclick="buscar()" class="btn btn-default" type="button"><span class="glyphicon glyphicon-search" aria-hidden="true"></span></button>
      </span>
    </div>





  </div><!-- /.col-lg-6 -->
  <!--/div><!-- /.row -->




      <!--/div>
      
    </div-->

