<div class="container" ng-controller="editnoticiaCtrl">

	<ol class="breadcrumb">
		  <li><a href="<?php echo $this->baseUrl('/'); ?>">Inicio</a></li>
		  <li><a href="<?php echo $this->baseUrl('/administrador/'); ?>">Administrador</a></li>
		  <li class="active">Editar</li>
	</ol>

    <h1 class="page-header">Editar Perfil</h1>
    
    <div class="row">



<!--++++++++++++++++++++ Comienzo del formulario ++++++++++++++++++-->
<div class="col-sm-12">
	<form id="form_noticia" name="form_noticia" enctype="multipart/form-data" action="<?php echo $this->baseUrl('/administrador/edit'); ?>" method="post"><div>

		<input type="hidden" id="id" name="id"  value="<?php echo $this->elemento['id']; ?>">

		<div id="idNoticia" data-id="<?php echo $this->elemento['id']; ?>"></div>

		


		<div class="form-group">
			<label for="cedula" class="required">Nombre *</label>
			<input type="text" name="name" id="name" value="<?php echo $this->elemento['name']; ?>" class="form-control" placeholder="Nombre">
		</div>

		<div class="form-group">
			<label for="cedula" class="required">Apellido *</label>
			<input type="text" name="lastname" id="lastname" value="<?php echo $this->elemento['lastname']; ?>" class="form-control" placeholder="Apellido">
		</div>

		<div class="form-group">
			<label for="cedula" class="required">Email *</label>
			<input type="text" name="email" id="email" value="<?php echo $this->elemento['email']; ?>" class="form-control" placeholder="Email">
		</div>

		<div class="form-group">
			<label for="cedula" class="required">Telefono *</label>
			<input type="text" name="telefono" id="telefono" value="<?php echo $this->elemento['telefono']; ?>" class="form-control" placeholder="Telefono">
		</div>

		<div class="form-group">
			<label for="cedula" class="required">Movil *</label>
			<input type="text" name="movil" id="movil" value="<?php echo $this->elemento['movil']; ?>" class="form-control" placeholder="Movil">
		</div>

		<div class="form-group">
		<label for="estado" class="required">Estado  *</label>

			<select name="estado" id="estado" class="form-control">
			    
			            <option value="">--Estado--</option>
			                    <?php foreach ($this->estados as $state): ?>
			                    <option value="<?php echo $state->id; ?>" <?php echo (isset($this->elemento['state_id']) && $this->elemento['state_id']== $state->id) ? 'selected' : ''; ?>><?php echo utf8_encode($state->state); ?></option>
			                    <?php endforeach; ?>


			</select>
		</div>





		<div class="col-sm-12">	
				<div id="doc_path-label col-sm-9">
		<label for="doc_path" class="optional">Imagen Destacada:</label>
		</div>
		<div id="doc_path-element">
			<input type="hidden" name="MAX_FILE_SIZE" value="2097152" id="MAX_FILE_SIZE">
			<input type="file" name="doc_path" id="doc_path" class="btn">
			Tamaño Maximo de Imagen 1Mb. Cambie la Imagen solo si requiere actualizarla
		</div>

		<div class="col-sm-3">
		<img src="<?php echo $this->baseUrl('assets/img/').$this->elemento['imagen']; ?>" class="img ig-responsive img-form" max-width="100px" >
			
		</div>

		</div>
		

		



		<dt id="buttons-label">&#160;</dt>
		<dd id="buttons-element">
			<fieldset id="fieldset-buttons">
				<dl>
					<input type="submit" name="btn_submit" id="btn_submit" value="Guardar" class="btn btn-default">

					<button name="btn_cancel" id="btn_cancel" type="button" class="btn btn-danger">Cancelar</button>
				</dl>

			</fieldset>
		</dd>
		</div>
	</form> 


</div>




   






<!--+++<?php// echo $this->EstForm; ?> ++++++++++++++++++++ Fin  del formulario+++++++++++++++ ++++++++++++-->










    </div> <!-- fin row -->
    
</div> <!-- fin container  -->
