




  <!--banner-->
  <div class="content">
    <div class="serach-w3agile">
      <div class="container">
        <h3 class="tittle">Buscar Propiedades</h3>
        <div class="place-grids">
         

 
           <div class="clearfix"></div>
          <br>


          <input class="filtros" type="hidden" name="f_estado" id="f_estado">
          <input class="filtros" type="hidden" name="f_ciudad" id="f_ciudad">
          <input class="filtros" type="hidden" name="f_municipio" id="f_municipio">
          <input  class="filtros" type="hidden" name="f_parroquia" id="f_parroquia">
        




          <div class="row">
  <div class="col-lg-8 col-lg-offset-2">

      <select id="tipo_propiedad" name="tipo_propiedad" class=" col-sm-3 selectpicker form-control input-lg" data-live-search="true" title="Tipos de Propiedades">
                        <option value="">Todo</option>
                        <option value="Apartamento">Apartamento</option>
                        <option value="Casa">Casa</option>
                        <option value="Local Comercial">Local Comercial</option>
                        <option value="Galpon">Galpon</option>
                        <option value="Residencia">Residencia</option>
                    </select>

      <div class="input-group input-group-lg">
      <input style="border-radius: 0px;" type="text"  id="autocomplete" name="autocomplete" class="col-sm-9 form-control" placeholder="Buscar Propiedades" onFocus="geolocate()">
      <span class="input-group-btn">
        <button id="btn_buscar" name="btn_buscar" onclick="buscar()" class="btn btn-default" type="button"><span class="glyphicon glyphicon-search" aria-hidden="true"></span></button>
      </span>
    </div>





  </div><!-- /.col-lg-6 -->
  </div><!-- /.row -->
  </div><!-- /.row -->








        </div>
      </div>
    </div>
    
    <div class="popular-w3">
      <div class="container">
        
        <div class="popular-grids">

        <?php $ObjFotos = new Application_Model_DbTable_Fotos(); ?>



        <?php foreach ($this->inmueble as $inm): ?>
          <?php $foto=$ObjFotos->getsSolicitudUna($inm->id);  ?>  

          <div class="col-md-4 popular-grid">
            <h4><?php echo $inm->tipo_inmueble; ?></h4>
            <img src="<?php echo $this->baseUrl('/assets/images/').$foto->foto; ?>" class="img-responsive" alt=""/>
            <div class="popular-text">
              <h3><a href="<?php echo $this->baseUrl('/inmueble/ver/id/').$inm->id; ?>"><?php echo $inm->titulo; ?></a></h3>
              <a href="#" class="button"><?php echo $inm->monto_vender; ?> BS.</a>
              <div class="detail-bottom">
                  

             <ul>          
            <li class="col-sm-3"><i  title="Area de Construcción" class="fa fa-arrows-alt fa-2x" aria-hidden="true"></i> <?php echo $inm->contruccion; ?>  </li>
            <li class="col-sm-3">  <i title="Habitacones" class="fa fa-bed fa-2x" aria-hidden="true"></i> <?php echo $inm->habitaciones; ?></li>
            <li class="col-sm-3"><i title="Baños" class="fa fa-shower fa-2x" aria-hidden="true"></i><?php echo $inm->banos; ?>  </li>
            <li class="col-sm-3"><i title="Puestos de Estacionamiento"  class="fa fa-car fa-2x" aria-hidden="true"></i> <?php echo $inm->puestos; ?>  </li>
            </ul> 
            <p> </p>
                
                
              </div>
            </div>
          </div>

          
        <?php endforeach ?>

        
          <div class="clearfix"></div>
        </div>
      </div>
    </div>
    <!--popular-->
















<!DOCTYPE html>
<html>
  <head>
    <title>Place Autocomplete Address Form</title>
    <meta name="viewport" content="initial-scale=1.0, user-scalable=no">
    <meta charset="utf-8">
    <style>
      /* Always set the map height explicitly to define the size of the div
       * element that contains the map. */
      #map {
        height: 100%;
      }
      /* Optional: Makes the sample page fill the window. */
      html, body {
        height: 100%;
        margin: 0;
        padding: 0;
      }
    </style>
    <link type="text/css" rel="stylesheet" href="https://fonts.googleapis.com/css?family=Roboto:300,400,500">
    <style>
      #locationField, #controls {
        position: relative;
        width: 480px;
      }
      #autocomplete {
        position: absolute;
        top: 0px;
        left: 0px;
        width: 99%;
      }
      .label {
        text-align: right;
        font-weight: bold;
        width: 100px;
        color: #303030;
      }
      #address {
        border: 1px solid #000090;
        background-color: #f0f0ff;
        width: 480px;
        padding-right: 2px;
      }
      #address td {
        font-size: 10pt;
      }
      .field {
        width: 99%;
      }
      .slimField {
        width: 80px;
      }
      .wideField {
        width: 200px;
      }
      #locationField {
        height: 20px;
        margin-bottom: 2px;
      }
    </style>
  </head>

  <body>
    <div id="locationField">
     <!-- <input id="autocomplete" placeholder="Enter your address"
             onFocus="geolocate()" type="text"></input> -->
    </div>

    <table id="address">
      <tr>
        <td class="label">Street address</td>
        <td class="slimField"><input class="field" id="street_number"
              disabled="true"></input></td>
        <td class="wideField" colspan="2"><input class="field" id="route"
              disabled="true"></input></td>
      </tr>
      <tr>
        <td class="label">City</td>
        <!-- Note: Selection of address components in this example is typical.
             You may need to adjust it for the locations relevant to your app. See
             https://developers.google.com/maps/documentation/javascript/examples/places-autocomplete-addressform
        -->
        <td class="wideField" colspan="3"><input class="field" id="locality"
              disabled="true"></input></td>
      </tr>
      <tr>
        <td class="label">State</td>
        <td class="slimField"><input class="field"
              id="administrative_area_level_1" disabled="true"></input></td>
        <td class="label">Zip code</td>
        <td class="wideField"><input class="field" id="postal_code"
              disabled="true"></input></td>
      </tr>
      <tr>
        <td class="label">Country</td>
        <td class="wideField" colspan="3"><input class="field"
              id="country" disabled="true"></input></td>
      </tr>
    </table>

    <script>
      // This example displays an address form, using the autocomplete feature
      // of the Google Places API to help users fill in the information.

      // This example requires the Places library. Include the libraries=places
      // parameter when you first load the API. For example:
      // <script src="https://maps.googleapis.com/maps/api/js?key=YOUR_API_KEY&libraries=places">

      var placeSearch, autocomplete;
      var componentForm = {
        street_number: 'short_name',
        route: 'long_name',
        locality: 'long_name',
        administrative_area_level_1: 'short_name',
        country: 'long_name',
        postal_code: 'short_name'
      };

      function initAutocomplete() {
        // Create the autocomplete object, restricting the search to geographical
        // location types.
        autocomplete = new google.maps.places.Autocomplete(
            /** @type {!HTMLInputElement} */(document.getElementById('autocomplete')),
            {types: ['geocode']});

        // When the user selects an address from the dropdown, populate the address
        // fields in the form.
        autocomplete.addListener('place_changed', fillInAddress);
      }

      function fillInAddress() {
        // Get the place details from the autocomplete object.
        var place = autocomplete.getPlace();

        for (var component in componentForm) {
          document.getElementById(component).value = '';
          document.getElementById(component).disabled = false;
        }

        // Get each component of the address from the place details
        // and fill the corresponding field on the form.
        for (var i = 0; i < place.address_components.length; i++) {
          var addressType = place.address_components[i].types[0];
          if (componentForm[addressType]) {
            var val = place.address_components[i][componentForm[addressType]];
            document.getElementById(addressType).value = val;
          }
        }
      }

      // Bias the autocomplete object to the user's geographical location,
      // as supplied by the browser's 'navigator.geolocation' object.
      function geolocate() {
        if (navigator.geolocation) {
          navigator.geolocation.getCurrentPosition(function(position) {
            var geolocation = {
              lat: position.coords.latitude,
              lng: position.coords.longitude
            };
            var circle = new google.maps.Circle({
              center: geolocation,
              radius: position.coords.accuracy
            });
            autocomplete.setBounds(circle.getBounds());
          });
        }
      }
    </script>
    <script src="https://maps.googleapis.com/maps/api/js?key=AIzaSyDEuMEkRLqwBtFieb8f3wzbxHyrYU8myP8&libraries=places&callback=initAutocomplete"
        async defer></script>
  </body>
</html>