<?php
$id=$this->modulo['id'];
$titulo=$this->modulo['titulo'];
$descripcion=$this->modulo['descripcion'];
$imagen=$this->modulo['imagen'];
$estatus=$this->modulo['estatus'];

//var_dump($this->servicio);
 ?>


<td><?php echo $id; ?></td>
            
            <td><?php echo $titulo; ?></td>
            <td><?php echo $descripcion; ?></td>
            <td><img src="<?php echo $this->baseUrl($imagen); ?>" class="img img-responsive" width="90px"> </td>

            <td>
                
                <div class="btn-group pull-right">

                    
                    <a href="<?php echo $this->baseUrl('/marcas/edit/id/').$id; ?>"  class="btn btn-primary"><span class="glyphicon glyphicon-edit"></span> </a>
                    <button type="button" onclick="del(<?php echo $id; ?>)"  class="btn btn-danger" title="Eliminar"><span class="glyphicon glyphicon-trash"></span> </button>

                    <?php if ($estatus){ ?>

                      <button type="button"  onclick="desactivarServicio(<?php echo $id; ?> )"  class="btn btn-default" title="Eliminar"><span class="glyphicon  glyphicon-thumbs-up"></span> </button>  

                    <?php }else{ ?>

                        <button type="button" onclick="activarServicio(<?php echo $id; ?>)"  class="btn btn-default" title="Eliminar"><span class="glyphicon  glyphicon-thumbs-down"></span> </button>  

                    <?php } ?>

                    
                </div>
                
                
                
                
            </td>
