<div class="container">
    
   <div class="panel panel-primary">
        <div class="panel-content">
            <div class="panel-header">
                <?php echo $this->noticias['titulo'];  ?>
            </div>

            <div class="panel-body">
                cuerppo
            </div>

            <div class="panel-footer">
                footer
            </div>



        </div>

       
   </div>

    
	
	
   
	
		
    
    
</div>

<div id="approveModal" class="modal fade">
    <div class="modal-dialog">
        <div class="modal-content">
            <div class="modal-header">
                <button type="button" class="close" data-dismiss="modal" aria-hidden="true">&times;</button>
                <h4 class="modal-title">Aprobar Miembro</h4>
            </div>
            <div class="modal-body">
                <p>¿Seguro desea realizar esta acción?</p>
                <p class="debug-url"></p>
            </div>
            <div class="modal-footer">
                <button type="button" class="btn btn-default" data-dismiss="modal">Cancelar</button>
                <button type="button" class="btn btn-primary approve">Aceptar</button>
                <form id="formApprove" name="formApprove" method="POST" action="<?php echo $this->url(array('controller' => 'members', 'action' => 'approve')); ?>">
                    <input type="hidden" id="mid" name="mid" value="">
                </form>
            </div>
        </div>
    </div>
</div>

<div id="rejectModal" class="modal fade">
    <div class="modal-dialog">
        <div class="modal-content">
            <div class="modal-header">
                <button type="button" class="close" data-dismiss="modal" aria-hidden="true">&times;</button>
                <h4 class="modal-title">Rehazar Miembro</h4>
            </div>
            <div class="modal-body">
                <p>¿Seguro desea realizar esta acción?</p>
                <p class="debug-url"></p>
            </div>
            <div class="modal-footer">
                <button type="button" class="btn btn-default" data-dismiss="modal">Cancelar</button>
                <button type="button" class="btn btn-danger reject">Aceptar</button>
                <form id="formReject" name="formReject" method="POST" action="<?php echo $this->url(array('controller' => 'members', 'action' => 'reject')); ?>">
                    <input type="hidden" id="mid" name="mid" value="">
                </form>
            </div>
        </div>
    </div>
</div>

<div id="pendingModal" class="modal fade">
    <div class="modal-dialog">
        <div class="modal-content">
            <div class="modal-header">
                <button type="button" class="close" data-dismiss="modal" aria-hidden="true">&times;</button>
                <h4 class="modal-title">Cambiar estatus de miembro</h4>
            </div>
            <div class="modal-body">
                <p>¿Está seguro que desea cambiar el estatus del miembro a pendiente?</p>
                <p class="debug-url"></p>
            </div>
            <div class="modal-footer">
                <button type="button" class="btn btn-default" data-dismiss="modal">Cancelar</button>
                <button type="button" class="btn btn-primary pending">Aceptar</button>
                <form id="formPending" name="formPending" method="POST" action="<?php echo $this->url(array('controller' => 'members', 'action' => 'pending')); ?>">
                    <input type="hidden" id="mid" name="mid" value="">
                </form>
            </div>
        </div>
    </div>
</div>

<div id="deleteModal" class="modal fade">
    <div class="modal-dialog">
        <div class="modal-content">
            <div class="modal-header">
                <button type="button" class="close" data-dismiss="modal" aria-hidden="true">&times;</button>
                <h4 class="modal-title">Eliminar miembro</h4>
            </div>
            <div class="modal-body">
                <p>¿Está seguro que desea eliminar el miembro?</p>
                <p class="debug-url"></p>
            </div>
            <div class="modal-footer">
                <button type="button" class="btn btn-default" data-dismiss="modal">Cancelar</button>
                <button type="button" class="btn btn-danger delete">Borrar</button>
                <form id="formDelete" name="formDelete" method="POST" action="<?php echo $this->url(array('controller' => 'estudiantes', 'action' => 'delete')); ?>">
                    <input type="hidden" id="id" name="id" value="">
                </form>
            </div>
        </div>
    </div>
</div>

