<!DOCTYPE html>

<html class="visible-xs">

<head>

  <meta http-equiv="Content-Type" content="text/html; charset=ISO-8859-1" />

  <html lang="es">

  <title><?php echo $this->meta['titulo']; ?> </title>

  <!-- Facebook and Twitter integration -->

  <meta property="og:url"           content="<?php echo $this->meta['url']; ?>" />

  <meta property="og:type"          content="website" />

  <meta property="og:title"         content="<?php echo $this->meta['titulo']; ?>" />

  <meta property="og:description"   content="<?php echo $this->meta['descripcion']; ?>" />

  <meta property="og:image"         content="<?php echo $this->meta['imagen']; ?>" />


  <meta name="twitter:title" content="encasaplus.com" />

  <meta name="twitter:image" content="" />
  
  <meta name="twitter:url" content="https://twitter.com/encasaplus" />
  
  <meta name="twitter:card" content="@encasaplus" />

  <?php

    $directorio = 'assets/diseno/css/';
    $css = scandir($directorio); 

    $directorio_js = 'assets/diseno/js/';
    $js = scandir($directorio_js); 

  ?>

    <?php foreach ($css as $c ): ?>
      <?php if ($c=='.' or $c=='..'){ ?>
      <?php }else{ ?>
          <link href="<?php echo $this->baseUrl('/assets/diseno/css/'.$c); ?>" rel="stylesheet" >
      <?php } ?>
    <?php endforeach ?>


    <!--css-->

<link href="<?php echo $this->baseUrl('/assets/css/jquery-ui.css'); ?>" rel="stylesheet" >






<!--/web-fonts-->
<link href="//fonts.googleapis.com/css?family=Poppins:300,400,500,600,700" rel="stylesheet">
<link href='//fonts.googleapis.com/css?family=Roboto:400,100,100italic,300,300italic,400italic,500,500italic,700,700italic,900,900italic' rel='stylesheet' type='text/css'>





<link rel="apple-touch-icon" sizes="57x57" href="<?php echo $this->baseUrl('/'); ?>favicon/apple-icon-57x57.png">
<link rel="apple-touch-icon" sizes="60x60" href="<?php echo $this->baseUrl('/'); ?>favicon/apple-icon-60x60.png">
<link rel="apple-touch-icon" sizes="72x72" href="<?php echo $this->baseUrl('/'); ?>favicon/apple-icon-72x72.png">
<link rel="apple-touch-icon" sizes="76x76" href="<?php echo $this->baseUrl('/'); ?>favicon/apple-icon-76x76.png">
<link rel="apple-touch-icon" sizes="114x114" href="<?php echo $this->baseUrl('/'); ?>favicon/apple-icon-114x114.png">
<link rel="apple-touch-icon" sizes="120x120" href="<?php echo $this->baseUrl('/'); ?>favicon/apple-icon-120x120.png">
<link rel="apple-touch-icon" sizes="144x144" href="<?php echo $this->baseUrl('/'); ?>favicon/apple-icon-144x144.png">
<link rel="apple-touch-icon" sizes="152x152" href="<?php echo $this->baseUrl('/'); ?>favicon/apple-icon-152x152.png">
<link rel="apple-touch-icon" sizes="180x180" href="<?php echo $this->baseUrl('/'); ?>favicon/apple-icon-180x180.png">
<link rel="icon" type="image/png" sizes="192x192"  href="<?php echo $this->baseUrl('/'); ?>favicon/android-icon-192x192.png">
<link rel="icon" type="image/png" sizes="32x32" href="<?php echo $this->baseUrl('/'); ?>favicon/favicon-32x32.png">
<link rel="icon" type="image/png" sizes="96x96" href="<?php echo $this->baseUrl('/'); ?>favicon/favicon-96x96.png">
<link rel="icon" type="image/png" sizes="16x16" href="<?php echo $this->baseUrl('/'); ?>favicon/favicon-16x16.png">
<link rel="manifest" href="/manifest.json">
<meta name="msapplication-TileColor" content="#ffffff">
<meta name="msapplication-TileImage" content="/ms-icon-144x144.png">
<meta name="theme-color" content="#ffffff">
<!--css-->
<meta name="viewport" content="width=device-width, initial-scale=1">

<meta name="keywords" content="<?php  echo $this->identidad['palabras']; ?>" />

<script type="application/x-javascript"> addEventListener("load", function() { setTimeout(hideURLbar, 0); }, false); function hideURLbar(){ window.scrollTo(0,1); } </script>
<!--js-->

</head>

<body class="bg">

  <div id="fb-root"></div>

  <script>(function(d, s, id) {
  var js, fjs = d.getElementsByTagName(s)[0];
  if (d.getElementById(id)) return;
  js = d.createElement(s); js.id = id;
  js.src = "//connect.facebook.net/es_LA/sdk.js#xfbml=1&version=v2.10&appId=153625785193462";
  fjs.parentNode.insertBefore(js, fjs);
}(document, 'script', 'facebook-jssdk'));</script>

<script src="https://apis.google.com/js/platform.js" async defer>
  {lang: 'es-419'}
</script>





	<div class="overlay overlay-simplegenie">
			<button type="button" class="overlay-close"><i class="fa fa-times" aria-hidden="true"></i></button>
			<nav>
				<ul>
					<li><a href="<?php echo $this->baseUrl('/'); ?>">Home</a></li>
					<li><a href="<?php echo $this->baseUrl('#'); ?>">Nosotros</a></li>
					<li><a href="<?php echo $this->baseUrl('#'); ?>">Noticias</a></li>
					<li><a href="<?php echo $this->baseUrl('/inmueble/buscar'); ?>">Propiedades</a></li>
					<li><a href="<?php echo $this->baseUrl('#'); ?>">Servicios</a></li>
					<li><a href="<?php echo $this->baseUrl('#'); ?>">Contacto</a></li>
				</ul>
			</nav>
		</div>
		<section class="header-w3ls"> 
			<button id="trigger-overlay" type="button"><i class="fa fa-bars" aria-hidden="true"></i></button>
			<div class="bottons-agileits-w3layouts">

        <?php $auth = Zend_Auth::getInstance(); ?>

        <?php if ($auth->hasIdentity()){ ?>

        	<?php $role_id=$auth->getIdentity()->role_id; ?>

        <?php  ?>

        	<?php if ($role_id=='5'){?>

        		<a class="page-scroll" href="<?php echo $this->baseUrl('/areacliente') ?>" data-toggle="modal"><i class="fa fa-sign-in" aria-hidden="true"></i>Area Cliente</a>.
        		
        	<?php }else{ ?>

        		<a class="page-scroll" href="<?php echo $this->baseUrl('/areaasesor') ?>" data-toggle="modal"><i class="fa fa-sign-in" aria-hidden="true"></i>Area Asesor</a>.

        	<?php } ?>

        	

        	<a class="page-scroll" href="<?php echo $this->baseUrl('/auth/logout') ?>" data-toggle="modal"><i class="fa fa-sign-in" aria-hidden="true"></i>Salir</a>.

			

        <?php }else{ ?>


        	<a class="page-scroll" href="<?php echo $this->baseUrl('/login') ?>" data-toggle="modal"><i class="fa fa-sign-in" aria-hidden="true"></i>Login</a>.

			<a class="page-scroll" href="<?php echo $this->baseUrl('/registro') ?>" data-toggle="modal"><i class="fa fa-pencil-square-o" aria-hidden="true"></i>Registro</a>

        <?php } ?>



			</div>
			<?php if (isset($this->logo)){ ?>
			<h1 style="width: 100%;     padding-left: 2em;"><a href="<?php echo $this->baseUrl('/'); ?>"><img class="img img-responsive" src="http://encasaplus.com/android/assets/images/EnCasaPlusBlanco.png" alt="En casa Plus."></a></h1>

			
		<?php }else{ ?>

		<h1><a href="<?php echo $this->baseUrl('/'); ?>">En Casa Plus</a></h1>


		<?php } ?>

		<div class="clearfix"> </div>
		</section>
<!-- //menu -->



        <?php echo $this->layout()->content; ?>

        <!-- footer section -->
<!--footer-->


<!-- footer -->
	<div class="footer" style="    position: fixed;    /* height: 100px; */    bottom: 0;
    width: 100%;">
		
		<div class="agileinfo_footer_bottom1">
			<div class="container">
					

			<div class="row" style="text-align: center; color: #fff;  font-size: 1.5em;">


				<div class="col-xs-4">
		    		<a alt="Propiedades" style="color: #fff;" href="<?php echo $this->baseUrl('inmueble/buscar') ?>"><i class="fa fa-home"></i></a>
		    	</div>
		    	<div class="col-xs-4">
		    		<a alt="Buscar Propiedades" style="color: #fff;" href="<?php echo $this->baseUrl('areacliente/buscar') ?>"><i class="fa fa-search"></i></a>
		    		
		    	</div>



		        <?php $auth = Zend_Auth::getInstance(); ?>

		        <?php if ($auth->hasIdentity()){ ?>

		        	<div class="col-xs-4">
		    		<a alt="Area Cliente" style="color: #fff;" href="<?php echo $this->baseUrl('areacliente') ?>"><i class="fa fa-user"></i></a>
		    		
		    	</div>

		        <?php }else{ ?>

		        	<div class="col-xs-4">
		    		<a alt="Area Cliente" style="color: #fff;" href="<?php echo $this->baseUrl('login') ?>"><i class="fa fa-user"></i></a>
		    		
		    	</div>

		        <?php } ?>

		    	
		    	
		    	
    	
    	</div>
    </div>



				<div class="clearfix"> </div>
			</div>
		</div>
	</div>
<!-- //footer -->

  <?php foreach ($js as $j ): ?>
      <?php if ($j=='.' or $j=='..'){ ?>
      <?php }else{ ?>
        <script src="<?php echo $this->baseUrl('/assets/diseno/js/'.$j); ?>"></script>
      <?php } ?>
    <?php endforeach ?>





		<script>
						// You can also use "$(window).load(function() {"
						$(function () {
						  // Slideshow 4
						  $("#slider4").responsiveSlides({
							auto: true,
							pager:true,
							nav:false,
							speed: 500,
							namespace: "callbacks",
							before: function () {
							  $('.events').append("<li>before event fired.</li>");
							},
							after: function () {
							  $('.events').append("<li>after event fired.</li>");
							}
						  });
					
						});
			</script>
			<script>
							// You can also use "$(window).load(function() {"
							$(function () {
							  // Slideshow 3
							  $("#slider3").responsiveSlides({
								auto: true,
								pager:false,
								nav: true,
								speed: 500,
								namespace: "callbacks",
								before: function () {
								  $('.events').append("<li>before event fired.</li>");
								},
								after: function () {
								  $('.events').append("<li>after event fired.</li>");
								}
							  });
						
							});
						  </script>





<script src="<?php echo $this->baseUrl('/assets/js/upload.js'); ?>"></script>


</body>

</html>

