<!DOCTYPE html>
<html lang="es">
    <head>
        <base href="<?php echo $this->baseUrl(); ?>">
        <meta charset="utf-8">
        <meta http-equiv="X-UA-Compatible" content="IE=edge">
        <meta name="viewport" content="width=device-width, initial-scale=1">
        <link rel="shortcut icon" type="image/x-icon" href="<?php echo $this->baseUrl('/assets/img/favicon.ico'); ?>">
        <link href='http://fonts.googleapis.com/css?family=Open+Sans:600italic,400,800,700,300' rel='stylesheet' type='text/css'>
    <link href='http://fonts.googleapis.com/css?family=BenchNine:300,400,700' rel='stylesheet' type='text/css'>
        <title>M&M International Group</title>
        <link href="<?php echo $this->baseUrl('/assets/css/bootstrap.min.css'); ?>" rel="stylesheet">
        <link href="<?php echo $this->baseUrl('/assets/css/font-awesome.min.css'); ?>" rel="stylesheet">
        <link href="<?php echo $this->baseUrl('/assets/css/style.css'); ?>" rel="stylesheet">
        <!--[if lt IE 9]>
        <script src="https://oss.maxcdn.com/libs/html5shiv/3.7.0/html5shiv.js"></script>
        <script src="https://oss.maxcdn.com/libs/respond.js/1.4.2/respond.min.js"></script>
        <![endif]-->





    </head>
    <body>

        <!-- ============   header section -->
    <header class="top-header">
        <div class="container">
            <div class="row">
                <div class="col-xs-5 header-logo">
                    <br>
                    <a href="mminternationalgroup.com/"><img src="<?php echo $this->baseUrl('/assets/img/logo_apaisado.jpg'); ?>" alt="" class="img-responsive logo"></a>
                </div>

                <div class="col-md-7">
                    <nav class="navbar navbar-default">
                      <div class="container-fluid nav-bar">
                        <!-- Brand and toggle get grouped for better mobile display -->
                        <div class="navbar-header">
                          <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#bs-example-navbar-collapse-1">
                            <span class="sr-only">Toggle navigation</span>
                            <span class="icon-bar"></span>
                            <span class="icon-bar"></span>
                            <span class="icon-bar"></span>
                          </button>
                        </div>

                        <!-- Collect the nav links, forms, and other content for toggling -->
                        <div class="collapse navbar-collapse" id="bs-example-navbar-collapse-1">
                          
                          <ul class="nav navbar-nav navbar-right">
                            <li><a class="menu active" href="#home" >Inicio</a></li>
                            <li><a class="menu" href="#about">Nosotros</a></li>
                            <li><a class="menu" href="#service">Servicios </a></li>
                            <li><a class="menu" href="#team">Equipo</a></li>
                            <li><a class="menu" href="#contact"> Contacto</a></li>
                          </ul>
                        </div><!-- /navbar-collapse -->
                      </div><!-- / .container-fluid -->
                    </nav>
                </div>
            </div>
        </div>
    </header> <!-- end of header area -->


        <?php echo $this->layout()->content; ?>


       <!-- footer starts here -->
            <footer class="footer clearfix">
                <div class="container">
                    <div class="row">



                               <div class="col-sm-3">  
                            <h3>  Noticias</h3>
                    <div class="media">
                      <div class="media-left">
                        <a href="#">
                          <img class="media-object" src="<?php echo $this->baseUrl('/assets/img/noticia2.jpg'); ?>" width="64" alt="...">
                        </a>
                      </div>
                      <div class="media-body">
                        <h4 class="media-heading">Titulo Noticia</h4>
                      </div>
                    </div>


                    <div class="media">
                      <div class="media-left">
                        <a href="#">
                          <img class="media-object" src="<?php echo $this->baseUrl('/assets/img/noticia1.jpg'); ?>" width="64" alt="...">
                        </a>
                      </div>
                      <div class="media-body">
                        <h4 class="media-heading">Titulo Noticia</h4>
                      </div>
                    </div>

                    <div class="media">
                      <div class="media-left">
                        <a href="#">
                          <img class="media-object" src="<?php echo $this->baseUrl('/assets/img/noticia3.jpg'); ?>" width="64" alt="...">
                        </a>
                      </div>
                      <div class="media-body">
                        <h4 class="media-heading">Titulo Noticia 2</h4>
                      </div>
                    </div>
                     </div>

                    <div class="col-sm-3 intereses">
                            <h3>   Interes</h3>

                            <ul id="enlaces">
                                <li><a href="servicios">Quienes Somos</a></li>
                                <li><a href="servicios">Productos</a></li>
                                <li> <a href="servicios">Servicios</a></li>

                                <li><a href="servicios">Contacto</a></li>

                            </ul>
                            
                       </div>
                
                    <div class="col-sm-3 contacto_footer ">
                         <h3>Informacion de Contacto</h3>
                  <div class="info-detail">
                    <ul><li><i class="fa fa-calendar"></i>  <span>Horario de Atencion:</span> 9:30 AM a 6:30 PM</li></ul>
                    <ul><li><i class="fa fa-map-marker"></i>  <span>Direccion:</span> Calle 1 San Andres Caracas</li></ul>
                    <ul><li><i class="fa fa-phone"></i>  <span>Telefono:</span> (0212) 999-1235</li></ul>
                    <ul><li><i class="fa fa-fax"></i>  <span>Fax:</span> (0212) 999-1234</li></ul>
                    <ul><li><i class="fa fa-envelope"></i>  <span>Email:</span> info@mminternationalgroup.com</li></ul>
                  </div>
                    </div>


                    <div class="col-sm-3 ">

                     <h3>Nuestras Redes</h3>
                        
                            <div class="col-sm-4 col-xs-4">
                                <img src="<?php echo $this->baseUrl('/assets/img/redes/facebook.png'); ?>" class="img img-responsive">
                            </div>
                            <div class="col-sm-4 col-xs-4">
                                <img src="<?php echo $this->baseUrl('/assets/img/redes/twitter.png'); ?>" class="img img-responsive">
                            </div>
                            <div class="col-sm-4 col-xs-4">
                                <img src="<?php echo $this->baseUrl('/assets/img/redes/insta.png'); ?>" class="img img-responsive">
                            </div>
                            
                       

                    </div>
















                        <!--<div class="col-xs-6 footer-para">
                            <p>&copy;freshDesignweb.com All right reserved</p>
                        </div>

                        <div class="col-xs-6 text-right">
                            <a href=""><i class="fa fa-facebook"></i></a>
                            <a href=""><i class="fa fa-twitter"></i></a>
                            <a href=""><i class="fa fa-skype"></i></a>
                        </div>-->


                    </div>
                </div>
            </footer>

            

        <script src="<?php echo $this->baseUrl('/assets/js/jquery-2.1.1.js'); ?>"></script>
        <script src="<?php echo $this->baseUrl('/assets/js/bootstrap.min.js'); ?>"></script>
        <script src="<?php echo $this->baseUrl('/assets/js/gmaps.js'); ?>"></script>
        <script src="<?php echo $this->baseUrl('/assets/js/smoothscroll.js'); ?>"></script>
        <script src="<?php echo $this->baseUrl('/assets/js/custom.js'); ?>"></script>¿
       
    </body>
	
	
</html>