<?php




 ?>


 <div class="row">
 	
 	<div class="col-sm-6">
 		<div class="row">
 			
 			<button class="btn btn-default" onclick="caja()"> Volver</button>
 			<button class="btn btn-default" onclick="pagar()"> Pagar</button>
 			 <a target="_blank" class="btn btn-primary" href="wake/pedidos/detalle/id/<?php echo $this->pedido['id']; ?>"> Imprimir</a>
 		</div>

 		<div class="row">
 			<table class="table table-responsive">
 				<tr>
 					<td></td>
 					<td></td>

 					<td></td>

 					<td></td>

 					<td></td>

 					<td></td>

 				</tr>
 				<tr>
 					<td></td>
 					<td></td>

 					<td></td>

 					<td></td>

 					<td></td>

 					<td></td>
 					
 				</tr>
 				<tr>
 					<td></td>
 					<td></td>

 					<td></td>

 					<td></td>

 					<td></td>

 					<td></td>
 					
 				</tr>
 			</table>
 		</div>
 	</div>

 	<div class="col-sm-6">
 		<button   class="btn btn-sq-lg btn-primary">
                <br/>
                <span class="titulo" > Cerveza </span>
                <br/>
               <span class="total">Bs. 500</span>
        </button>

        <button   class="btn btn-sq-lg btn-primary">
                <br/>
                <span class="titulo" > Hora Wake </span>
                <br/>
               <span class="total">Bs. 4000</span>
        </button>
 	</div>
 </div>