	<div class="container">

	<ol class="breadcrumb">
		  <li><a href="#">Inicio</a></li>
		  <li><a href="app/paginas">Paginas</a></li>
		  <li class="active">Agregar</li>
	</ol>

    <h1 class="page-header">Agregar Pagina</h1>
    </div>
    <div class="row">



<!--++++++++++++++++++++ Comienzo del formulario ++++++++++++++++++-->
<div class="col-sm-12">
	<form id="form_noticia" name="form_noticia" enctype="multipart/form-data" action="<?php echo $this->baseUrl('/pagina/add'); ?>" method="post"><div>

		<input type="hidden" id="id" name="id"  value="<?php echo time();?>">

		<div id="idNoticia" data-id="<?php echo time();?>"></div>

		<div class="form-group">
			<label for="cedula" class="required">Grupo *</label>
			<input type="text"  name="grupo" id="grupo" value="" class="form-control" placeholder="Grupo">
		</div>


		<div class="form-group">
			<label for="cedula" class="required">Titulo *</label>
			<input type="text"  name="titulo" id="titulo" value="" class="form-control" placeholder="Titulo">
		</div>

		<div class="form-group">
			<label for="nombre" class="required">Contenido *</label>

			<textarea rows="10" ng-model="contenido" name="contenido" id="contenido" style="width: 100%;"></textarea>

		</div>





		<div id="doc_path-label">
		<label for="doc_path" class="optional">Imagen Destacada:</label>
		</div>
		<div id="doc_path-element">
			<input type="hidden" name="MAX_FILE_SIZE" value="2097152" id="MAX_FILE_SIZE">
			<input type="file" name="doc_path" id="doc_path" class="btn">
			Tamaño Maximo de Imagen 1Mb.
		</div>



		<dt id="buttons-label">&#160;</dt>
		<dd id="buttons-element">
			<fieldset id="fieldset-buttons">
				<dl>
					<input type="submit" name="btn_submit" id="btn_submit" value="Guardar" class="btn btn-default">

					<button name="btn_cancel" id="btn_cancel" type="button" class="btn btn-danger">Cancelar</button>
				</dl>

			</fieldset>
		</dd>
		</div>
	</form> 


</div>



   






<!--+++<?php// echo $this->EstForm; ?> ++++++++++++++++++++ Fin  del formulario+++++++++++++++ ++++++++++++-->










    </div> <!-- fin row -->
    
</div> <!-- fin container  -->
