<div class="container-fluid" ng-controller="slidersCtrl">

    <ol class="breadcrumb">
          <li><a href="#">Inicio</a></li>
         
          <li class="active">Sliders</li>
    </ol>


    <h1 class="page-header">Sliders

     <?php  if ($this->acceso['sliders']['add']): ?>

        <div class="pull-right">
                    <a href="<?php echo $this->baseUrl('/sliders/add'); ?>" class="btn btn-default"><span class="glyphicon glyphicon-user"></span> Crear Slider</a>
                </div>
<?php endif ?>

        
    </h1>
    
    <?php if (count($this->messages) > 0): ?>
        <div class="alert alert-success alert-dismissable">
            <button type="button" class="close" data-dismiss="alert" aria-hidden="true">&times;</button>
            <?php foreach ($this->messages as $message): ?>
                <span><?php echo current($message); ?></span><br>
            <?php endforeach; ?>
        </div>
    <?php endif; ?>
	
	 
    
    <table class="table table-striped">
        <tr>
            <th>ID</th>
            <th>Titulo</th>
            <th>Descripcion</th>
            <th>Imagen</th>
            <th>Pais</th>
        
            
            <th width="150px">
               Accion
            </th>
        </tr>

             <?php foreach ($this->sliders as $row): ?>
        <tr id="<?php echo $row->id; ?>">
            <td><?php echo $row->id; ?></td>
            
            <td><?php echo $row->titulo; ?></td>
            <td><?php echo $row->descripcion; ?></td>
            <td><img src="<?php echo $this->baseUrl('/').$row->imagen; ?>" class="img img-responsive" width="90px"> </td>


            <td>
                
                <?php if($row->pais=='1'){ ?>
                    Venezuela
                <?php }else{ ?>
                    Dominicana
                <?php } ?>

            </td>

            <td>
                
                <div class="btn-group pull-right">

                <?php  if (isset($this->acceso['sliders']['edit'])): ?>
                     <a href="<?php echo $this->baseUrl('/sliders/edit/id/').$row->id; ?>"  class="btn btn-primary"><span class="glyphicon glyphicon-edit"></span> </a>
                <?php endif ?>

                <?php  if (isset($this->acceso['sliders']['del'])): ?>
                          <button type="button" onclick="del(<?php echo $row->id; ?>)"  class="btn btn-danger" title="Eliminar"><span class="glyphicon glyphicon-trash"></span> </button>
                <?php endif ?>

                <?php  if (isset($this->acceso['sliders']['del'])): ?>
                        <?php if ($row->estatus){ ?>

                      <button type="button"  onclick="desactivarSlider(<?php echo $row->id; ?> )"  class="btn btn-default" title="Eliminar"><span class="glyphicon  glyphicon-thumbs-up"></span> </button>  

                    <?php }else{ ?>

                        <button type="button" onclick="activarSlider(<?php echo $row->id; ?>)"  class="btn btn-default" title="Eliminar"><span class="glyphicon  glyphicon-thumbs-down"></span> </button>  

                    <?php } ?>
                <?php endif ?>
                    
                    

                

                  
                </div>
                
            </td>


        </tr>
        <?php endforeach; ?>
       
       
        
    </table>
    

<div id="deleteModal" class="modal fade">
    <div class="modal-dialog">
        <div class="modal-content">
            <div class="modal-header">
                <button type="button" class="close" data-dismiss="modal" aria-hidden="true">&times;</button>
                <h4 class="modal-title">Eliminar</h4>
            </div>
            <div class="modal-body">
                <input type="hidden" name="del_id" id="del_id">
                <p>¿Está seguro que desea eliminar el registro?</p>
                <p class="debug-url"></p>
            </div>
            <div class="modal-footer">
                <button type="button" class="btn btn-default" data-dismiss="modal">Cancelar</button>
                <button type="button" onclick="deleteSlider()" class="btn btn-danger">Borrar</button>
                
            </div>
        </div>
    </div>
</div>





</div> <!-- End Container--> 