
<div class="w3l_agileits_breadcrumbs">
   <div class="container">
    <div class="w3l_agileits_breadcrumbs_inner">
      <ul>
        <li><a href="<?php echo $this->baseUrl('/'); ?>">Home</a><span>«</span></li>
                  
        <li>Area Cliente</li>
        </ul>
    </div>
  </div>
</div>    

<!--Services-->
<div class="options-wthree">
    <div class="container">
    <ul>
      <li>
      <a href="<?php echo $this->baseUrl('/inmueble/buscar'); ?>" class="opt-grids">
        <div class="icon-agileits-w3layouts">
          <i class="fa fa-home" aria-hidden="true"></i>
        </div>
        <div class="opt-text-w3layouts">
          <h6>Ver Propiedades</h6>
        </div>
      </a>
      </li>
      <li>
      <a href="<?php echo $this->baseUrl('/areacliente/solicitud'); ?>" class="opt-grids">
        <div class="icon-agileits-w3layouts">
          <i class="fa fa-clipboard" aria-hidden="true"></i>
        </div>
        <div class="opt-text-w3layouts">
          <h6>Solicitar Propiedad</h6>
        </div>
      </a>
      </li>
      <li>
      <a href="<?php echo $this->baseUrl('/areacliente/missolicitudes'); ?>" class="opt-grids">
        <div class="icon-agileits-w3layouts">
          <i class="fa fa-list" aria-hidden="true"></i>
        </div>
        <div class="opt-text-w3layouts">
          <h6>Mis Solicitudes</h6>
        </div>
      </a>
      </li>


      <li>
      <a href="<?php echo $this->baseUrl('/areacliente/add'); ?>" class="opt-grids">
        <div class="icon-agileits-w3layouts">
          <i class="fa fa-clipboard" aria-hidden="true"></i>
        </div>
        <div class="opt-text-w3layouts">
          <h6>Cargar Propiedad</h6>
        </div>
      </a>
      </li>
      
      <li>
      <a href="<?php echo $this->baseUrl('/areacliente/mispropiedades'); ?>" class="opt-grids">
        <div class="icon-agileits-w3layouts">
          <i class="fa fa-list" aria-hidden="true"></i>
        </div>
        <div class="opt-text-w3layouts">
          <h6>Mis Propiedades</h6>
        </div>
      </a>
      </li>
     
     
      <li>
      <a href="<?php echo $this->baseUrl('/auth/logout'); ?>" class="opt-grids">
        <div class="icon-agileits-w3layouts">
          <i class="fa fa-sign-out" aria-hidden="true"></i>
        </div>
        <div class="opt-text-w3layouts">
          <h6>Salir</h6>
        </div>
      </a>
      </li>






    </ul>
  </div>
</div>
