<!DOCTYPE html PUBLIC "-//W3C//DTD HTML 4.01 Transitional//EN">
<html>
    <head>
        <meta charset="utf-8">
        <title>Reporte</title>
        <style>
            body {font-size: 11px;}
        </style>
    </head>
    <body>
        <h2>Reporte de Cursos</h2>
        
        <table cellpadding="2" cellspacing="2" border="0">
            <tr style="background-color: #BDBDBD; font-weight: bold; color:white;">
                <th width="10%" height="30px" style="border-right: 1px solid #ccc;">Id</th>
                <th width="10%" height="30px" style="border-right: 1px solid #ccc;">Código</th>
                <th width="60%" height="30px" style="border-right: 1px solid #ccc;">Descripción</th>
                <th width="20%" height="30px" style="border-right: 1px solid #ccc;">Duración en Horas</th>
            </tr>
            <?php $i=0; foreach ($this->cursos as $row): $i++; ?>
                <tr style="font-size:10px; background-color: <?php echo ($i%2==0) ? '#eee;' : '#fff'; ?>;">


                    <td height="30px" style="border-right: 1px solid #ccc;"><?php echo $row->id; ?></td>
                    <td height="30px" style="border-right: 1px solid #ccc;"><?php echo utf8_encode($row->codigo); ?></td>
                    <td height="30px" style="border-right: 1px solid #ccc;"><?php echo utf8_encode(ucwords($row->descripcion)); ?></td>
                     <td height="30px" style="border-right: 1px solid #ccc;"><?php echo utf8_encode($row->duracion); ?> Horas</td>
                </tr>
            <?php endforeach; ?>
        </table>
    </body>
</html>