
<div class="featured-section" id="projects">
  <div class="container">
        
       
        <h3 class="tittle">  <?php echo $this->pagina['titulo']; ?> </h3>
         <div class="content-bottom-in terminos" style="text-align: justify; line-height: 2em;">

         <?php echo $this->pagina['contenido']; ?>
      

        

        
          <div class="clearfix"></div>
        </div>
      </div>
    </div>
    <!--popular-->
