<div class="container-fluid">
    <h1 class="page-header">Registro de Empleados</h1>
    
    <div class="row">




            <!--++++++++++++++++++++ Comienzo del formulario ++++++++++++++++++-->

<form id="form_clientes" name="form_estudiantes" enctype="multipart/form-data" action="wake/empleados/edit" method="post"><div>
<input type="hidden" id="id" name="id" value="<?php echo $this->id;?>">
<div class="form-group"><label for="cedula" class="required">Cédula *</label>

<input type="text" name="cedula" id="cedula" value="<?php echo $this->dcedula;?>" class="form-control" placeholder="Cédula"></div>
<div class="form-group"><label for="nombre" class="required">Nombre *</label>

<input type="text" name="nombre" id="nombre" value="<?php echo $this->dnombre;?>" class="form-control span3" placeholder="Nombre"></div>




<div class="form-group"><label for="email" class="optional">Email</label>

<input type="text" name="email" id="email" value="<?php echo $this->demail;?>" class="form-control" placeholder="ej: john@gmail.com" required="1"></div>

<div class="form-group"><label for="fecha_nac" class="required">Fecha de Nacimiento *</label>

<input type="text" name="fecha_nac" id="fecha_nac" value="<?php echo $this->dfecha_nac;?>" class="form-control fecha" placeholder="Fecha de Nacimiento"></div>

<div class="form-group"><label for="estado" class="required">Estado  *</label>

<select name="estado" id="estado" class="form-control">
    
            <option value="">--Estado--</option>
                    <?php foreach ($this->states as $state): ?>
                    <option value="<?php echo $state->id; ?>" <?php echo (isset($this->destado) && $this->destado== $state->id) ? 'selected' : ''; ?>><?php echo utf8_encode($state->state); ?></option>
                    <?php endforeach; ?>


</select></div>



<div class="form-group"><label for="direccion" class="required">Dirección  *</label>

<input type="text" name="direccion" id="direccion" value="<?php echo $this->ddireccion;?>" class="form-control" placeholder="Dirección"></div>
<div class="form-group"><label for="tlf" class="required">Teléfono  *</label>

<input type="text" name="tlf" id="tlf" value="<?php echo $this->dtlf;?>" class="form-control" placeholder="Teléfono"></div>










<div id="buttons-label">&#160;</div><div id="buttons-element"><fieldset id="fieldset-buttons"><div>

<input type="submit" name="btn_submit" id="btn_submit" value="Guardar" class="btn btn-default">

<a href="wake/empleados" name="btn_cancel" id="btn_cancel" type="button" class="btn btn-danger">Cancelar</a>
</div></fieldset></div></div></form> 





    </div>
    
</div>
