<div class="container-fluid">
    
    <h1 class="page-header">
	
		Empleados Registrados
	
		<div class="pull-right col-xs-4 col-md-4 col-sm-6">
			<a href="<?php echo $this->url(array('controller' => 'empleados', 'action' => 'add')); ?>"  class="btn btn-primary"><span class="glyphicon glyphicon-user"></span> Agregar</a>

			
		</div>
	
	
	</h1>

    <?php if (count($this->messages) > 0): ?>
        <div class="alert alert-success alert-dismissable">
            <button type="button" class="close" data-dismiss="alert" aria-hidden="true">&times;</button>
            <?php foreach ($this->messages as $message): ?>
                <span><?php echo current($message); ?></span><br>
            <?php endforeach; ?>
        </div>
    <?php endif; ?>
    
	
	
   
	
		<table class="table table-hover table-striped" id="tb_estudiantes">
        <thead style="backgroun"><tr>
            <th>Id</th>
             <th>Cédula</th>
            <th>Nombre</th>
            <th>Dirección </th>
            <th>Estado</th>
           
            <th>Fecha de Nacimiento</th>
            <th>Email</th>
            
            <th class="text-center" width="17%">Acción</th>
        </tr></thead><tbody>
        <?php foreach ($this->empleados as $row): ?>
		
		

            <tr>
                <td><?php echo $row->id; ?></td>
                <td><?php echo $row->cedula; ?></td>
                <td><?php echo ucwords(implode(' ', array($row->nombre))); ?></td>
                <td><?php echo utf8_encode(ucwords($row->direccion)); ?></td>
                <td><?php echo utf8_encode(ucwords($row->estado)); ?></td>
                <td><?php echo utf8_encode($row->fecha_nac); ?></td>
                <td><?php echo utf8_encode($row->email); ?></td>
               
                <td class="text-center">
                    <div id="actiongroup" class="btn-group">
                        
                        <a href="<?php echo $this->url(array('controller' => 'empleados', 'action' => 'edit', 'id' => $row->id)); ?>" class="btn btn-info btn-sm" title="Editar"><span class="glyphicon glyphicon-edit"></span> </a>

                        <button type="button" data-id="<?php echo $row->id; ?>" data-toggle="modal" data-target="#deleteModal" class="btn btn-danger btn-sm delete" title="Eliminar"><span class="glyphicon glyphicon-trash"></span></button>
                        

                    </div>
                </td>
            </tr>
        <?php endforeach; ?>
		</tbody>
	</table>
    
    
</div>


<div id="deleteModal" class="modal fade">
    <div class="modal-dialog">
        <div class="modal-content">
            <div class="modal-header">
                <button type="button" class="close" data-dismiss="modal" aria-hidden="true">&times;</button>
                <h4 class="modal-title">Eliminar Empleado</h4>
            </div>
            <div class="modal-body">
                <p>¿Está seguro que desea eliminar el Empleado?</p>
                <p class="debug-url"></p>
            </div>
            <div class="modal-footer">
                <button type="button" class="btn btn-default" data-dismiss="modal">Cancelar</button>
                <button type="button" class="btn btn-danger delete">Borrar</button>
                <form id="formDelete" name="formDelete" method="POST" action="<?php echo $this->url(array('controller' => 'empleado', 'action' => 'delete')); ?>">
                    <input type="hidden" id="id" name="id" value="">
                </form>
            </div>
        </div>
    </div>
</div>

