<!DOCTYPE html>
<html lang="es">
    <head>
        <base href="<?php echo $this->baseUrl(); ?>">
        <meta charset="utf-8">
        <meta http-equiv="X-UA-Compatible" content="IE=edge">
        <meta name="viewport" content="width=device-width, initial-scale=1">
        <link rel="shortcut icon" type="image/x-icon" href="<?php echo $this->baseUrl('/assets/img/favicon.ico'); ?>">
        <!--<link href='http://fonts.googleapis.com/css?family=Open+Sans:600italic,400,800,700,300' rel='stylesheet' type='text/css'>
    <link href='http://fonts.googleapis.com/css?family=BenchNine:300,400,700' rel='stylesheet' type='text/css'>-->
        <title>Horus Wakeboarding</title>
        <link href="<?php echo $this->baseUrl('/assets/css/bootstrap.min.css'); ?>" rel="stylesheet">
        <link href="<?php echo $this->baseUrl('/assets/css/font-awesome.min.css'); ?>" rel="stylesheet">

        <link href="<?php echo $this->baseUrl('/assets/css/custom.css'); ?>" rel="stylesheet">
        <link href="<?php echo $this->baseUrl('/assets/css/style-admin.css'); ?>" rel="stylesheet">
        <!--[if lt IE 9]>
        <script src="https://oss.maxcdn.com/libs/html5shiv/3.7.0/html5shiv.js"></script>
        <script src="https://oss.maxcdn.com/libs/respond.js/1.4.2/respond.min.js"></script>
        <![endif]-->

         </head>
    <body>

<?php $auth = Zend_Auth::getInstance(); ?>
        <?php if ($auth->hasIdentity()): ?>

    <div id="wrapper">
        <nav class="navbar navbar-default navbar-cls-top " role="navigation" style="margin-bottom: 0">
            <div class="navbar-header">
                <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".sidebar-collapse">
                    <span class="sr-only">Toggle navigation</span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                </button>
                <a class="navbar-brand" href="wake/">Admin </a> 
            </div>
  <div style="color: white;
padding: 15px 50px 5px 50px;
float: right;
font-size: 16px;"> Bienvenido: <?php echo $auth->getIdentity()->username; ?> &nbsp; <a href="<?php echo $this->baseUrl('/auth/logout'); ?>" class="btn btn-danger square-btn-adjust">Cerrar Session</a> </div>
        </nav>   
           <!-- /. NAV TOP  -->
                <nav class="navbar-default navbar-side" role="navigation">
            <div class="sidebar-collapse">
                <ul class="nav" id="main-menu">
                <li class="text-center">
                    <img src="<?php echo $this->baseUrl('/assets/img/logo_apaisado.jpg'); ?>" class="user-image img-responsive"/>
                    </li>
                            <li><a href="<?php echo $this->baseUrl('/pedidos/caja'); ?>"><i class="fa fa-money fa-2x"></i> Ventas</a></li>
                            <li><a href="<?php echo $this->baseUrl('/clientes'); ?>"><i class="fa fa-users fa-2x"></i> Clientes</a></li>
                            <li><a href="<?php echo $this->baseUrl('/pedidos'); ?>"><i class="fa fa-shopping-cart fa-2x"></i> Ventas</a></li>
                            <li><a href="<?php echo $this->baseUrl('/productos'); ?>"><i class="fa fa-qrcode fa-2x"></i> Productos</a></li>
                            <li><a href="<?php echo $this->baseUrl('/users'); ?>"><i class="fa fa-user fa-2x"></i>Usuarios</a></li>
                
                </ul>
               
            </div>
            
        </nav>  

        <?php endif; ?>        <!-- /. NAV SIDE  -->
        <div id="page-wrapper" >
            <div class="" id="page-inner">
               <div class="" >    
               
                <?php echo $this->layout()->content; ?>

                    </div>

                </div>
             <!-- /. PAGE INNER  -->
            </div>
         <!-- /. PAGE WRAPPER  -->
        </div>
     <!-- /. WRAPPER  -->



   















        
    
        <script src="<?php echo $this->baseUrl('/assets/js/jquery-2.1.1.js'); ?>"></script>
        <script src="<?php echo $this->baseUrl('/assets/js/bootstrap.min.js'); ?>"></script>
        <script src="<?php echo $this->baseUrl('/assets/js/gmaps.js'); ?>"></script>
        <script src="<?php echo $this->baseUrl('/assets/js/smoothscroll.js'); ?>"></script>

        <script src="<?php echo $this->baseUrl('/assets/js/jquery.metisMenu.js'); ?>"></script>
        <script src="<?php echo $this->baseUrl('/assets/js/custom-layout.js'); ?>"></script>
        

        <script src="<?php echo $this->baseUrl('/assets/js/smoothscroll.js'); ?>"></script>
<!--<script src="<?php echo $this->baseUrl('/assets/js/morris/raphael-2.1.0.min.js'); ?>"></script>
<script src="<?php echo $this->baseUrl('/assets/js/morris.js'); ?>"></script>-->
<script src="<?php echo $this->baseUrl('/assets/js/dataTables/jquery.dataTables.js'); ?>"></script>
<script src="<?php echo $this->baseUrl('/assets/js/dataTables/dataTables.bootstrap.js'); ?>"></script>




        <script src="<?php echo $this->baseUrl('/assets/js/custom-admin.js'); ?>"></script>¿
       
    </body>
	
	
</html>