<div class="container-fluid">
    <h1 class="page-header">Inicio</h1>
  
  <br>
  <br>
    





        
      <div class="row">
        <div class="col-lg-12">
          <p>

            <a href="<?php echo $this->baseUrl('/clientes'); ?>" class="btn btn-sq-lg btn-primary">
                <br/>
                <span class="glyphicon glyphicon-user ">  </span>
                <br/>
                Clientes 
            </a>

            <a href="<?php echo $this->baseUrl('/productos'); ?>" class="btn btn-sq-lg btn-success">
                <br/><span class="glyphicon glyphicon-gift ">  </span>
                <br/>
                Productos
            </a>


            <a href="<?php echo $this->baseUrl('/pedidos'); ?>" class="btn btn-sq-lg btn-info">
               <br/><span class="glyphicon glyphicon-shopping-cart ">  </span>
                <br/>
              Ventas
            </a>

            <!--
            <a href="<?php echo $this->baseUrl('/mensajes'); ?>" class="btn btn-sq-lg btn-warning">
               <br/><span class="glyphicon glyphicon-envelope ">  </span>
                <br/>
              Mensajes
            </a>

            <a href="<?php echo $this->baseUrl('/grupos'); ?>" class="btn btn-sq-lg btn-default">
               <br/><span class="glyphicon glyphicon-th ">  </span>
                <br/>
              Grupos
            </a>-->


            <a href="<?php echo $this->baseUrl('/users'); ?>" class="btn btn-sq-lg btn-danger">
              <br/><span class="glyphicon glyphicon-cog ">  </span>
                <br/>
              Usuarios
            </a>
          </p>
        </div>
  </div>
  

  









</div>
