<div class="container">

  <ol class="breadcrumb">
      <li><a href="<?php echo $this->baseUrl('/'); ?>">Inicio</a></li>
      <li><a href="<?php echo $this->baseUrl('/presupuesto'); ?>">Presupuestos</a></li>
      <li class="active">Ver Detalle</li>
  </ol>
    
   <div class="row">

   <h1 class="page-header">Detalles de la Solicitud de Presupuestos</h1>

   <br> 

   <table class="table table-striped table-responsive"> 
      <tr>  
      <th > Campo </th>
      <th> Detalle </th>

      </tr>

      <tr>  
        <th> Id </th>
        <td> <?php echo $this->presupuesto['id']; ?>  </td>
      </tr>

      <tr>  
        <th> Nombres y Apellidos </th>
        <td> <?php echo $this->presupuesto['nombres'].' '.$this->presupuesto['apellidos']; ?>  </td>
      </tr>

      <tr>  
        <th> Telefono Local  </th>
        <td> <?php echo $this->presupuesto['tlf']; ?>  </td>
      </tr>

      <tr>  
        <th> Telefono Movil </th>
        <td> <?php echo $this->presupuesto['tlf_movil']; ?>  </td>
      </tr>

      <tr>  
        <th> Email </th>
        <td> <?php echo $this->presupuesto['email']; ?>  </td>
      </tr>
      

      <tr>  
        <th> Empresa </th>
        <td> <?php echo $this->presupuesto['empresa']; ?>  </td>
      </tr>
        
      
      <tr>  
        <th> Rif </th>
        <td> <?php echo $this->presupuesto['rif']; ?>  </td>
      </tr>

      <tr>  
        <th> Ciudad </th>
        <td> <?php echo $this->presupuesto['ciudad']; ?>  </td>
      </tr>

      <tr>  
        <th> Tipo  </th>
        <td> <?php echo $this->presupuesto['tipo']; ?>  </td>
      </tr>

      <tr>  
        <th> Cantidad </th>
        <td> <?php echo $this->presupuesto['cantidad']; ?>  </td>
      </tr>

      <tr>  
        <th> Descripcion </th>
        <td> <?php echo $this->presupuesto['descripcion']; ?>  </td>
      </tr>

      <tr>  
        <th> Fecha </th>
        <td> <?php echo $this->presupuesto['fecha']; ?>  </td>
      </tr>


    </table>


       
 

   

   </div>
   
    
	
	
   
	
		
    
    
</div>

