<div class="container" >

	<ol class="breadcrumb">
		  <li><a href="<?php echo $this->baseUrl('/'); ?>">Inicio</a></li>
		  <li><a href="<?php echo $this->baseUrl('/estados/list'); ?>">Estados</a></li>
		  <li class="active">Agregar Municipio</li>
	</ol>

    <h1 class="page-header">Agregar Municipio</h1>
    
    <div class="row">



<!--++++++++++++++++++++ Comienzo del formulario ++++++++++++++++++-->
<div class="col-sm-12">
	<form id="form_noticia" name="form_noticia" enctype="multipart/form-data" action="<?php echo $this->baseUrl('/estados/addmunicipio'); ?>" method="post"><div>

		<input type="hidden" id="id" name="id"  value="<?php echo time();?>">
		<input type="hidden" id="id_estado" name="id_estado"  value="<?php echo $this->id_estado; ?>">


		


		<div class="form-group">
			<label for="cedula" class="required">Municipio *</label>
			<input type="text" name="municipio" id="municipio" value="" class="form-control" placeholder="Municipio">
		</div>

		



		<dt id="buttons-label">&#160;</dt>
		<dd id="buttons-element">
			<fieldset id="fieldset-buttons">
				<dl>
					<input type="submit" name="btn_submit" id="btn_submit" value="Guardar" class="btn btn-default">

					<button name="btn_cancel" id="btn_cancel" type="button" class="btn btn-danger">Cancelar</button>
				</dl>

			</fieldset>
		</dd>
		</div>
	</form> 


</div>




   






<!--+++<?php// echo $this->EstForm; ?> ++++++++++++++++++++ Fin  del formulario+++++++++++++++ ++++++++++++-->










    </div> <!-- fin row -->
    
</div> <!-- fin container  -->
