
<section class="page-crumb">
    <div class="container">
        <!-- Page Heading/Breadcrumbs -->
        <div class="row">
            <div class="col-lg-12">
        <ol class="breadcrumb">
                    <li><a href="<?php echo $this->baseUrl('/'); ?>">Home</a>
                    </li>
                    <li><a href="<?php echo $this->baseUrl('/solicitud'); ?>">Solicitudes</a>
                    </li>
                    <li class="active">Presupuesto</li>
                </ol>
            </div>
        </div>
        <!-- /.row -->
  </div>
</section>


<section class="service-w3ls">
  <h3 class="text-center w3layouts w3 w3l w3ls agileits-w3layouts agile w3-agile">Solicitud Online</h3>
  <p class="text-center w3layouts w3 w3l w3ls agileits-w3layouts agile w3-agile">Formulario de Solicitud de valoracion online para Bienes Muebles.</p> 
  <div class="container"> 
        <!-- Service Panels -->
        <div class="row">

        <div class="col-sm-2"></div>
        <div class="col-sm-8">

        <form id="form_mueble" name="form_mueble" enctype="multipart/form-data" action="<?php echo $this->baseUrl('/solicitud/mueble'); ?>" method="post"><div>

    <input type="hidden" id="id" name="id"  value="<?php echo time();?>">

    <div class="row">
      


    

    <div class="page-header">
      <h1>Datos del Solicitante</h1>
    </div>

    <div class="form-group col-sm-6">
      <label for="cedula" class="required">Nombres *</label>
      <input type="text"  name="nombres" id="nombres" value="" class="form-control" placeholder="Nombres">
    </div>

    <div class="form-group col-sm-6">
      <label for="cedula" class="required">Apellidos *</label>
      <input type="text"  name="apellidos" id="apellidos" value="" class="form-control" placeholder="Apellidos">
    </div>

    <div class="form-group col-sm-6">
      <label for="cedula" class="required">Cedula de Identidad </label>
      <input type="text"  name="cedula" id="cedula" value="" class="form-control" placeholder="Ej: V-00000000">
    </div>

    <div class="form-group col-sm-6">
      <label for="cedula" class="required">Telefono Local *</label>
      <input type="text"  name="tlf" id="tlf" value="" class="form-control" placeholder="Telefono ">
    </div>

    <div class="form-group col-sm-6">
      <label for="cedula" class="required">Telefono Movil *</label>
      <input type="text"  name="tlf_movil" id="tlf_movil" value="" class="form-control" placeholder="Telefono  Movil">
    </div>

    <div class="form-group col-sm-6">
      <label for="cedula" class="required">Email *</label>
      <input type="text"  name="email" id="email" value="" class="form-control" placeholder="Correo Electronico">
    </div>

     <div class="form-group col-sm-6">
      <label for="cedula" class="required">Cantidad </label>
      <input type="text"  name="cantidad" id="cantidad" value="" class="form-control" placeholder="Cantidad">
    </div>

    </div>

    <div class="row">

    <div class="page-header">
      <h3>Direccion del Inmueble donde se encuentran los bienes a valorar</h3>
    </div>



    <div class="form-group col-sm-6">
      <label for="cedula" class="required">Estado </label>
      <input type="text"  name="estado" id="estado" value="" class="form-control" placeholder="Estado">
    </div>

    <div class="form-group col-sm-6">
      <label for="cedula" class="required">Ciudad </label>
      <input type="text"  name="ciudad" id="ciudad" value="" class="form-control" placeholder="Ciudad">
    </div>

    <div class="form-group col-sm-12">
      <label for="cedula" class="required">Direccion </label>
      <textarea rows="5"  name="direccion" id="direccion" style="width: 100%;"></textarea>
    </div>

    </div>

    <div class="row">


    <div class="page-header">
      <h3>Datos de los Bienes</h3>
    </div>



    <div class="form-group col-sm-6">
      <label for="cedula" class="required">Tipo</label>
      <input type="text"  name="tipo_bien" id="tipo_bien" value="" class="form-control" placeholder="Tipo de Bien">
    </div>


<div class="form-group col-sm-6">
      <label for="cedula" class="required">Cantidad </label>
      <input type="text"  name="cantidad_bien" id="cantidad_bien" value="" class="form-control" placeholder="Cantidad">
    </div>


<div class="form-group col-sm-6">
      <label for="cedula" class="required">Marca </label>
      <input type="text"  name="marca" id="marca" value="" class="form-control" placeholder="Marca">
    </div>

    <div class="form-group col-sm-6">
      <label for="cedula" class="required">Modelo </label>
      <input type="text"  name="modelo" id="modelo" value="" class="form-control" placeholder="Modelo">
    </div>


    <div class="form-group col-sm-6">
      <label for="estado" class="required">Edad Años*</label>
      <select name="edad_bien" id="edad_bien" class="form-control">
            <option value="">--Edad--</option>

            <?php for ($i=1; $i <100 ; $i++) { ?>

              <option value="<?php echo $i; ?>"><?php echo $i; ?></option>

            <?php } ?>      
                
      </select>
    </div>


    <div class="form-group col-sm-6">
      <label for="estado" class="required">Estado de Conservacion*</label>
      <select name="conservacion_bien" id="conservacion_bien" class="form-control">
            <option value="">--Estado de Conservacion--</option>

              <option value="Excelente">Excelente</option>
              <option value="Muy Bueno">Muy Bueno</option>
              <option value="Bueno">Bueno</option>
              <option value="Regular">Regular</option>
              <option value="Malo">Malo</option>
              <option value="Muy Malo">Muy Malo</option>
              <option value="Chatarra">Chatarra</option>


                
      </select>
    </div>
 
     <div class="form-group col-sm-6">
      <label for="estado" class="required">Cambio de Tecnologia  *</label>
      <select name="tecnologia_bien" id="tecnologia_bien" class="form-control">
            <option value="">--Cambio de Tecnologia--</option>

              <option value="Misma Tecnologia">Misma Tecnologia</option>
              <option value="Algunos Cambios">Algunos Cambios</option>
              <option value="Cambios en Produccion">Cambios en Produccion</option>
              <option value="Cambios en Tecnologia">Cambios en Tecnologia</option>
              <option value="Cambios Importantes">Cambios Importantes</option>

                               
      </select>
    </div>

    <div class="form-group col-sm-6">
      <label for="estado" class="required">Tipo de Mantenimiento *</label>
      <select name="mantenimiento_bien" id="mantenimiento_bien" class="form-control">
            <option value="">--Tipo de Mantenimiento--</option>

              <option value="Perfecto">Perfecto</option>
              <option value="Riguroso">Riguroso</option>
              <option value="Normal">Normal</option>
              <option value="Tolerable">Tolerable</option>
              <option value="Inexistente">Inexistente</option>

                               
      </select>
    </div>

    <div class="form-group col-sm-6">
      <label for="estado" class="required">Tipo de Trabajo *</label>
      <select name="trabajo_bien" id="trabajo_bien" class="form-control">
            <option value="">--Tipo de Trabajo--</option>

              <option value="Extremo">Extremo</option>
              <option value="Pesado">Pesado</option>
              <option value="Normal">Normal</option>
              <option value="Leve">Leve</option>
              <option value="Nulo">Nulo</option>

                               
      </select>
    </div>

    </div>


    <div class="form-group col-sm-12">
      <label for="cedula" class="required">Observaciones y Comentarios </label>
      <textarea rows="5"  name="observacion_bien" id="observacion_bien" style="width: 100%;"></textarea>
    </div>



    <div class="carga"> </div>
    <div class="loader">  </div>

    <div id="fileuploader"> Cargar Imagenes
    </div>



    <dt id="buttons-label">&#160;</dt>
    <dd id="buttons-element">
      <fieldset id="fieldset-buttons">
        <dl>
          <input type="submit" name="btn_submit" id="btn_submit" value="Guardar" class="btn btn-default">

          <button name="btn_cancel" id="btn_cancel" type="button" class="btn btn-danger">Cancelar</button>
        </dl>

      </fieldset>
    </dd>
    </div>
  </form> 

  </div><!--  fin col-sm-6 -->


    </div>  
  </div>
</section>  

<section class="service-agile">
  <div class="container">
    <h3 class="text-center agileits agileinfo wthree w3-agileits">Avaluos</h3>
    <p class="text-center agileits agileinfo wthree w3-agileits">Un avalúo es la estimación del valor de un bien mueble o inmueble expresado en cifras monetarias de acuerdo a criterios, herramientas y a metodologías científicas adecuadas tomando en cuenta las condiciones físicas, características, ubicación, uso, conservación, mantenimiento, operatividad, funcionamiento, y de una indagación y análisis de mercado, para la fecha en que se realiza dicha estimación.  .</p> 
        <!-- Service Tabs -->
        <div class="row">
            <div class="col-lg-12">
                <ul id="myTab" class="nav nav-tabs nav-justified">
                    <?php $j=0; ?>
                    <?php foreach ($this->avaluos as $ava): ?>

                      <?php if ( $j!=0): ?>
                        <li class=""><a href="#service-<?php echo $ava->id; ?>" data-toggle="tab"> <?php echo $ava->titulo; ?></a>
                        </li>
                        <?php $j++; ?>
                      <?php endif ?>

                      <?php if ($j==0): ?>
                        <li class="active"><a href="#service-<?php echo $ava->id; ?>" data-toggle="tab"> <?php echo $ava->titulo; ?></a>
                        </li>
                        <?php $j++; ?>
                      <?php endif ?>
                       
                    <?php endforeach ?>

                    
                </ul>

                <div id="myTabContent" class="tab-content">
                    
                    <?php $j=0; ?>
                    <?php foreach ($this->avaluos as $ava): ?>

                      <?php if ( $j!=0): ?>

                      <div class="tab-pane fade" id="service-<?php echo $ava->id; ?>">
                        <h4><?php echo $ava->titulo; ?></h4>
                        <img class="img " alt="<?php echo $ava->titulo; ?>" title="<?php echo $ava->titulo; ?>" src="<?php echo $this->baseUrl($ava->imagen); ?>">
                        <?php echo $ava->descripcion; ?>
                    </div>

                        
                        <?php $j++; ?>
                      <?php endif ?>

                      <?php if ($j==0): ?>

                      <div class="tab-pane fade active in" id="service-<?php echo $ava->id; ?>">
                      
                        <h4><?php echo $ava->titulo; ?></h4>
                        <img class="img " alt="<?php echo $ava->titulo; ?>" title="<?php echo $ava->titulo; ?>" src="<?php echo $this->baseUrl($ava->imagen); ?>">
                        <?php echo $ava->descripcion; ?>
                        
                    </div>


                        
                        <?php $j++; ?>
                      <?php endif ?>
                       
                    <?php endforeach ?>



                   
                    
            </div>
        </div>
        <hr>
  </div>  
</section>  
