
<section class="page-crumb">
    <div class="container">
        <!-- Page Heading/Breadcrumbs -->
        <div class="row">
            <div class="col-lg-12">
        <ol class="breadcrumb">
                    <li><a href="<?php echo $this->baseUrl('/'); ?>">Home</a>
                    </li>
                    <li><a href="<?php echo $this->baseUrl('/solicitud'); ?>">Solicitudes</a>
                    </li>
                    <li class="active">Presupuesto</li>
                </ol>
            </div>
        </div>
        <!-- /.row -->
  </div>
</section>


<section class="service-w3ls">
  <h3 class="text-center w3layouts w3 w3l w3ls agileits-w3layouts agile w3-agile">Solicitud de Presupuesto de Avaluos</h3>
  <p class="text-center w3layouts w3 w3l w3ls agileits-w3layouts agile w3-agile">Formulario de Solicitud de presupuesto de avaluo.</p> 
  <div class="container"> 
        <!-- Service Panels -->
        <div class="row">

        <div class="col-sm-3"></div>
        <div class="col-sm-6">

        <form id="form_presupuesto" name="form_presupuesto" enctype="multipart/form-data" action="<?php echo $this->baseUrl('/solicitud/presupuesto'); ?>" method="post"><div>

    <input type="hidden" id="id" name="id"  value="<?php echo time();?>">

    <div class="form-group">
      <label for="cedula" class="required">Nombres *</label>
      <input type="text"  name="nombres" id="nombres" value="" class="form-control" placeholder="Nombres">
    </div>

    <div class="form-group">
      <label for="cedula" class="required">Apellidos *</label>
      <input type="text"  name="apellidos" id="apellidos" value="" class="form-control" placeholder="Apellido">
    </div>

    <div class="form-group">
      <label for="cedula" class="required">Telefono Local *</label>
      <input type="text"  name="tlf" id="tlf" value="" class="form-control" placeholder="Telefono ">
    </div>

    <div class="form-group">
      <label for="cedula" class="required">Telefono Movil *</label>
      <input type="text"  name="tlf_movil" id="tlf_movil" value="" class="form-control" placeholder="Telefono  Movil">
    </div>

    <div class="form-group">
      <label for="cedula" class="required">Email *</label>
      <input type="text"  name="email" id="email" value="" class="form-control" placeholder="Correo Electronico">
    </div>

    <div class="form-group">
      <label for="cedula" class="required">Empresa</label>
      <input type="text"  name="empresa" id="empresa" value="" class="form-control" placeholder="Nombre de la empresa">
    </div>


<div class="form-group">
      <label for="cedula" class="required">Rif </label>
      <input type="text"  name="rif" id="rif" value="" class="form-control" placeholder="Rif">
    </div>


<div class="form-group">
      <label for="cedula" class="required">Ciudad </label>
      <input type="text"  name="ciudad" id="ciudad" value="" class="form-control" placeholder="Ciudad">
    </div>

    <div class="form-group">
      <label for="cedula" class="required">Tipo de Bienes  </label>
      <input type="text"  name="tipo" id="tipo" value="" class="form-control" placeholder="Tipo de Bienes">
    </div>

    <div class="form-group">
      <label for="cedula" class="required">Cantidad </label>
      <input type="text"  name="cantidad" id="cantidad" value="" class="form-control" placeholder="Cantidad">
    </div>

    <div class="form-group">
      <label for="cedula" class="required">Descripcion del bien a valorar </label>
      <textarea rows="10"  name="descripcion" id="descripcion" style="width: 100%;"></textarea>
    </div>

    
    <div class="col-sm-12">
      
         <div class="carga"> </div>
    <div class="loader">  </div>

    <div id="fileuploader"> Cargar Imagenes
    </div>

    </div>



    <dt id="buttons-label">&#160;</dt>
    <dd id="buttons-element">
      <fieldset id="fieldset-buttons">
        <dl>
          <input type="submit" name="btn_submit" id="btn_submit" value="Guardar" class="btn btn-default">

          <button name="btn_cancel" id="btn_cancel" type="button" class="btn btn-danger">Cancelar</button>
        </dl>

      </fieldset>
    </dd>
    </div>
  </form> 

  </div><!--  fin col-sm-6 -->





    </div>  
  </div>
</section>  

<section class="service-agile">
  <div class="container">
    <h3 class="text-center agileits agileinfo wthree w3-agileits">Avaluos</h3>
    <p class="text-center agileits agileinfo wthree w3-agileits">Un avalúo es la estimación del valor de un bien mueble o inmueble expresado en cifras monetarias de acuerdo a criterios, herramientas y a metodologías científicas adecuadas tomando en cuenta las condiciones físicas, características, ubicación, uso, conservación, mantenimiento, operatividad, funcionamiento, y de una indagación y análisis de mercado, para la fecha en que se realiza dicha estimación.  .</p> 
        <!-- Service Tabs -->
        <div class="row">
            <div class="col-lg-12">
                <ul id="myTab" class="nav nav-tabs nav-justified">
                    <?php $j=0; ?>
                    <?php foreach ($this->avaluos as $ava): ?>

                      <?php if ( $j!=0): ?>
                        <li class=""><a href="#service-<?php echo $ava->id; ?>" data-toggle="tab"> <?php echo $ava->titulo; ?></a>
                        </li>
                        <?php $j++; ?>
                      <?php endif ?>

                      <?php if ($j==0): ?>
                        <li class="active"><a href="#service-<?php echo $ava->id; ?>" data-toggle="tab"> <?php echo $ava->titulo; ?></a>
                        </li>
                        <?php $j++; ?>
                      <?php endif ?>
                       
                    <?php endforeach ?>

                    
                </ul>

                <div id="myTabContent" class="tab-content">
                    
                    <?php $j=0; ?>
                    <?php foreach ($this->avaluos as $ava): ?>

                      <?php if ( $j!=0): ?>

                      <div class="tab-pane fade" id="service-<?php echo $ava->id; ?>">
                        <h4><?php echo $ava->titulo; ?></h4>
                        <img class="img " alt="<?php echo $ava->titulo; ?>" title="<?php echo $ava->titulo; ?>" src="<?php echo $this->baseUrl($ava->imagen); ?>">
                        <?php echo $ava->descripcion; ?>
                    </div>

                        
                        <?php $j++; ?>
                      <?php endif ?>

                      <?php if ($j==0): ?>

                      <div class="tab-pane fade active in" id="service-<?php echo $ava->id; ?>">
                      
                        <h4><?php echo $ava->titulo; ?></h4>
                        <img class="img " alt="<?php echo $ava->titulo; ?>" title="<?php echo $ava->titulo; ?>" src="<?php echo $this->baseUrl($ava->imagen); ?>">
                        <?php echo $ava->descripcion; ?>
                        
                    </div>


                        
                        <?php $j++; ?>
                      <?php endif ?>
                       
                    <?php endforeach ?>



                   
                    
            </div>
        </div>
        <hr>
  </div>  
</section>  
