<div class="container" >

	<ol class="breadcrumb">
		  <li><a href="<?php echo $this->baseUrl('/'); ?>">Inicio</a></li>
		  <li><a href="<?php echo $this->baseUrl('/ciudad/list'); ?>">Ciuadd</a></li>
		  <li class="active">Agregar</li>
	</ol>

    <h1 class="page-header">Agregar Ciudad</h1>
   
    <div class="row">



<!--++++++++++++++++++++ Comienzo del formulario ++++++++++++++++++-->
<div class="col-sm-12">
	<form id="form_noticia" name="form_noticia" enctype="multipart/form-data" action="<?php echo $this->baseUrl('/ciudad/add'); ?>" method="post"><div>

		<input type="hidden" id="id" name="id"  value="<?php echo time();?>">

		<div id="idNoticia" data-id="<?php echo time();?>"></div>


		<div class="form-group">
			<label for="cedula" class="required">estados *</label>
			<input type="text"  name="id_estado" id="id_estado" value="" class="form-control" placeholder="Estado">
		</div>

		<div class="form-group">
			<label for="cedula" class="required">Iso_3166-2 *</label>
			<input type="text"  name="iso_3166-2" id="iso_3166-2" value="" class="form-control" placeholder="Iso_3166-2">
		</div>




		<dt id="buttons-label">&#160;</dt>
		<dd id="buttons-element">
			<fieldset id="fieldset-buttons">
				<dl>
					<input type="submit" name="btn_submit" id="btn_submit" value="Guardar" class="btn btn-default">

					<button name="btn_cancel" id="btn_cancel" type="button" class="btn btn-danger">Cancelar</button>
				</dl>

			</fieldset>
		</dd>
		</div>
	</form> 


</div>






   






<!--+++<?php// echo $this->EstForm; ?> ++++++++++++++++++++ Fin  del formulario+++++++++++++++ ++++++++++++-->










    </div> <!-- fin row -->
    
</div> <!-- fin container  -->
