<div class="container" ng-controller="editnoticiaCtrl">

	<ol class="breadcrumb">
		  <li><a href="<?php echo $this->baseUrl('/'); ?>">Inicio</a></li>
		  <li><a href="<?php echo $this->baseUrl('/asesores/list'); ?>">Asesores</a></li>
		  <li class="active">Editar</li>
	</ol>

    <h1 class="page-header">Editar </h1>
    
    <div class="row">



<!--++++++++++++++++++++ Comienzo del formulario ++++++++++++++++++-->
<div class="col-sm-12">
	<form id="form_noticia" name="form_noticia" enctype="multipart/form-data" action="<?php echo $this->baseUrl('/asesores/edit'); ?>" method="post"><div>

		<input type="hidden" id="id" name="id"  value="<?php echo $this->elemento['id']; ?>">

		<div id="idNoticia" data-id="<?php echo $this->elemento['id']; ?>"></div>

		


		<div class="form-group">
			<label for="cedula" class="required">Nombre *</label>
			<input type="text" name="nombre" id="nombre" value="<?php echo $this->elemento['nombre']; ?>" class="form-control" placeholder="Nombre">
		</div>

		<div class="form-group">
			<label for="cedula" class="required">Nombre *</label>
			<input type="text" name="cargo" id="cargo" value="<?php echo $this->elemento['cargo']; ?>" class="form-control" placeholder="Cargo">
		</div>

		<div class="form-group">
			<label for="cedula" class="required">Telefono *</label>
			<input type="text" name="telefono" id="telefono" value="<?php echo $this->elemento['telefono']; ?>" class="form-control" placeholder="telefono">
		</div>

		<div class="form-group">
			<label for="cedula" class="required">Email *</label>
			<input type="text" name="email" id="email" value="<?php echo $this->elemento['email']; ?>" class="form-control" placeholder="Email">
		</div>

	





		<div class="col-sm-12">	
				<div id="doc_path-label col-sm-9">
		<label for="doc_path" class="optional">Imagen Destacada:</label>
		</div>
		<div id="doc_path-element">
			<input type="hidden" name="MAX_FILE_SIZE" value="5242880" id="MAX_FILE_SIZE">
			<input type="file" name="doc_path" id="doc_path" class="btn">
			Tamaño Maximo de Imagen 5Mb. Cambie la Imagen solo si requiere actualizarla
		</div>

		<div class="col-sm-3">
		<img src="<?php echo $this->baseUrl($this->elemento['imagen']); ?>" class="img ig-responsive img-form" style="max-width: 10em;" >
			
		</div>

		</div>
		

		



		<dt id="buttons-label">&#160;</dt>
		<dd id="buttons-element">
			<fieldset id="fieldset-buttons">
				<dl>
					<input type="submit" name="btn_submit" id="btn_submit" value="Guardar" class="btn btn-default">

					<button name="btn_cancel" id="btn_cancel" type="button" class="btn btn-danger">Cancelar</button>
				</dl>

			</fieldset>
		</dd>
		</div>
	</form> 


</div>




   






<!--+++<?php// echo $this->EstForm; ?> ++++++++++++++++++++ Fin  del formulario+++++++++++++++ ++++++++++++-->










    </div> <!-- fin row -->
    
</div> <!-- fin container  -->
