<section class="about-us">
  <h2 class="text-center w3layouts w3 w3l w3ls">Nosotros</h2>
  <span class="about-line"></span>
  <p class="text-center w3layouts w3 w3l w3ls">Contamos con un equipo de  Avaluadores con formación diversa en Avalúos Inmobiliarios y Mobiliarios .</p>
  <div class="container">
    <div class="row">
      <div class="col-lg-6 col-md-6 col-sm-6 about-w3ls1">
        <!-- ACCORDION -->
        <div class="panel-group" id="accordion" role="tablist" aria-multiselectable="true">
          <?php $i=1; ?>
          <?php foreach ($this->nosotros as $nos): ?>

            <?php if ($i!=1): ?>


                <div class="panel panel-default">
            <div class="panel-heading" role="tab" id="heading<?php echo $i; ?>">
              <a class="pa_italic collapsed" role="button" data-toggle="collapse" data-parent="#accordion" href="#collapse<?php echo $i; ?>" aria-expanded="false" aria-controls="collapse<?php echo $i; ?>">
                <h4 class="panel-title asd">
                  <span class="glyphicon glyphicon-menu-down" aria-hidden="true"></span><i class="glyphicon glyphicon-menu-up" aria-hidden="true"></i>
                  <?php echo $nos->titulo; ?>
                </h4> 
              </a>
            </div>
            <div id="collapse<?php echo $i; ?>" class="panel-collapse collapse" role="tabpanel" aria-labelledby="heading<?php echo $i; ?>">
              <div class="panel-body panel_text">
                <?php echo $nos->contenido; ?>
              </div>
            </div>
          </div>




              <?php $i++; ?>
            <?php endif ?>

            <?php if ($i==1): ?>
              <div class="panel panel-default">
            <div class="panel-heading" role="tab" id="heading<?php echo $i; ?>">
              <a class="pa_italic" role="button" data-toggle="collapse" data-parent="#accordion" href="#collapse<?php echo $i; ?>" aria-expanded="true" aria-controls="collapse<?php echo $i; ?>">
                <h4 class="panel-title asd">
                  <span class="glyphicon glyphicon-menu-down" aria-hidden="true"></span><i class="glyphicon glyphicon-menu-up" aria-hidden="true"></i>
                  <?php echo $nos->titulo; ?>
                </h4> 
              </a>
            </div>
            <div id="collapse<?php echo $i; ?>" class="panel-collapse collapse in" role="tabpanel" aria-labelledby="heading<?php echo $i; ?>">
              <div class="panel-body panel_text">
                <div class="scrollbar" id="style-2">
                  <?php echo $nos->contenido; ?>
                </div>
              </div>
            </div>
          </div>

          <?php $i++; ?>
          
            <?php endif ?>

            
          <?php endforeach ?>


          
        </div>
      </div>
      <div class="col-lg-6 col-md-6 col-sm-6 about-w3ls2">
        <div id="Fader" class="fader"> 

            <?php foreach ($this->nosotros as $nos): ?>
               <img class="slide img-responsive" src="<?php echo $this->baseUrl('/').$nos->imagen; ?>" alt="<?php echo $nos->titulo; ?>" title="<?php echo $nos->titulo; ?>"/> 
            <?php endforeach ?>

          <div class="fader_controls">
            <ul class="pager_list">
            </ul>
          </div>
        </div>
      </div>
    </div>
  </div>  
</section>
<!-- /about section -->


<!-- info section -->
<section class="info">
  <div class="container-fluid">
    <div class="row">
      <div class="col-lg-5 col-md-5 col-sm-5 info-w3ls1"><?php  $imagen=$this->atencion['imagen']; ?>
        <img src="<?php echo $this->baseUrl('/').$imagen; ?>" class="img-responsive" alt="<?php echo $this->atencion['titulo']; ?>" title="<?php echo $this->atencion['titulo']; ?>">
      </div>
      <div class="col-lg-7 col-md-7 col-sm-7 info-w3ls2">
        <div class="info-details">
          <h3><?php echo $this->atencion['titulo']; ?></h3>
          <?php echo $this->atencion['contenido']; ?>  
        </div>
      </div>
    </div>
  </div>
</section>
<!-- /info section -->

<section class="service-w3ls">
  <h3 class="text-center w3layouts w3 w3l w3ls agileits-w3layouts agile w3-agile">Servicios</h3>
  <p class="text-center w3layouts w3 w3l w3ls agileits-w3layouts agile w3-agile">Ponemos a su disposicion los siguientes servicios.</p> 
  <div class="container"> 
        <!-- Service Panels -->
        <div class="row">
      <?php foreach ($this->modulos as $ser): ?>

        <div class="col-lg-4 col-md-4 col-sm-6 serv-w3ls">
        <div class="thumbnail">
          <div class="hi-icon-wrap hi-icon-effect-5 hi-icon-effect-5a">
            <img class="img img-modulo " alt="<?php echo $ser->titulo; ?>" title="<?php echo $ser->titulo; ?>" src="<?php echo $this->baseUrl($ser->imagen); ?>">
            <!--<a href="#set-5" class="hi-icon hi-icon-mobile"><?php echo $ser->imagen ?></a>-->
          </div>
          <h4 class="text-center"><?php echo $ser->titulo ?></h4>
          <p class="serv-p1"><?php echo $ser->descripcion ?></p>
        </div>
      </div>

        
      <?php endforeach ?>


    </div>  
  </div>
</section>  

<section class="service-agile">
  <div class="container">
    <h3 class="text-center agileits agileinfo wthree w3-agileits">Avaluos</h3>
    <p class="text-center agileits agileinfo wthree w3-agileits">Un avalúo es la estimación del valor de un bien mueble o inmueble expresado en cifras monetarias de acuerdo a criterios, herramientas y a metodologías científicas adecuadas tomando en cuenta las condiciones físicas, características, ubicación, uso, conservación, mantenimiento, operatividad, funcionamiento, y de una indagación y análisis de mercado, para la fecha en que se realiza dicha estimación.  .</p> 
        <!-- Service Tabs -->
        <div class="row">
            <div class="col-lg-12">
                <ul id="myTab" class="nav nav-tabs nav-justified">
                    <?php $j=0; ?>
                    <?php foreach ($this->avaluos as $ava): ?>

                      <?php if ( $j!=0): ?>
                        <li class=""><a href="#service-<?php echo $ava->id; ?>" data-toggle="tab"> <?php echo $ava->titulo; ?></a>
                        </li>
                        <?php $j++; ?>
                      <?php endif ?>

                      <?php if ($j==0): ?>
                        <li class="active"><a href="#service-<?php echo $ava->id; ?>" data-toggle="tab"> <?php echo $ava->titulo; ?></a>
                        </li>
                        <?php $j++; ?>
                      <?php endif ?>
                       
                    <?php endforeach ?>

                    
                </ul>

                <div id="myTabContent" class="tab-content">
                    
                    <?php $j=0; ?>
                    <?php foreach ($this->avaluos as $ava): ?>

                      <?php if ( $j!=0): ?>

                      <div class="tab-pane fade" id="service-<?php echo $ava->id; ?>">
                        <h4><?php echo $ava->titulo; ?></h4>
                        <img class="img " alt="<?php echo $ava->titulo; ?>" title="<?php echo $ava->titulo; ?>" src="<?php echo $this->baseUrl($ava->imagen); ?>">
                        <?php echo $ava->descripcion; ?>
                    </div>

                        
                        <?php $j++; ?>
                      <?php endif ?>

                      <?php if ($j==0): ?>

                      <div class="tab-pane fade active in" id="service-<?php echo $ava->id; ?>">
                      
                        <h4><?php echo $ava->titulo; ?></h4>
                        <img class="img " alt="<?php echo $ava->titulo; ?>" title="<?php echo $ava->titulo; ?>" src="<?php echo $this->baseUrl($ava->imagen); ?>">
                        <?php echo $ava->descripcion; ?>
                        
                    </div>
                        <?php $j++; ?>
                      <?php endif ?>
                       
                    <?php endforeach ?>
                    
            </div>
        </div>
        <hr>
  </div>  
</section>  



<!-- partners section -->
<section class="partners">
  <div class="container">
    <h3 class="text-center">Nuestros Clientes</h3>
    <p class="text-center">Son éstas, algunas de las compañias que por nuestra experiencia y solvencia han confiado en Nosotros.</p>
    <div class="sliderfig">
      <ul id="flexiselDemo1"> 

      <?php foreach ($this->marcas as $row): ?>
         <li>
          <img src="<?php echo $this->baseUrl($row->imagen); ?>" alt="<?php echo $row->titulo; ?>" title="<?php echo $row->titulo; ?>" class="img-responsive" />
        </li>
      <?php endforeach ?>

      </ul>
    </div>
  </div>
</section>
<!-- /partners section -->
