




  <!--contact-->

  <div class="container">
    <div class="row">
      <div class="col-sm-12" style="text-align: center;">
        <h1>Registrate</h1>
      </div>
      

      <div class="col-sm-12">
        <div class="col-sm-12">
        </div>

        <form id="formRegistro" method="post" action="<?php echo $this->baseUrl('registro/postregistro') ?>" >
          <div class="form-group col-sm-12">
            <input class="form-control" type="text" id="nombre"  name="nombre" placeholder="Nombre" required="">
          </div>

           <div class="form-group col-sm-12">
            <input class="form-control" type="text" id="apellido"  name="apellido" placeholder="Apellido" required="">
          </div>

          <div class="form-group col-sm-12">
              <input class="form-control" type="mail" id="email" name="email" placeholder="Email" required="">
            
          </div>

          <div class="form-group col-sm-12">
              <input class="form-control" type="password" id="clave" name="clave" placeholder="Clave" required="">
            
          </div>

          <div class="form-group col-sm-12">
              <input class="form-control" type="password" id="reclave" name="reclave" placeholder="Reingrese Clave" required="">
            
          </div>

         
          <div class="respuesta"></div>

          <input type="submit" class="btn btn-primary"  value="Enviar" >
          
        </form>


      </div>
     
    </div>
  </div>

  <br><br>


