

 <!--/team-->
<div class="team" id="team">
         <div class="container">
       <h3 class="tittle">Nuestros <span>Servicios </span></h3>
       <!--/about-section-->
      



        <?php   $i=0; ?>
            <?php foreach ($this->servicios as $servicio): ?>

              <?php if ($i==0){ ?>
                
                  <div class="about-section agileits">

                  <div class="col-md-4 ab-left">
                      <div class="grid">
          
                          <img style="" src="<?php echo $this->baseUrl($servicio->imagen); ?>" alt=" " class="">
          
                      </div>
                      <div class="clearfix"> </div>
                  </div>
         
                  <div class="col-md-8 ab-text" style="text-align: left;">
                      <h4 class="tittle"><?php echo  $servicio->titulo; ?></h4>
                      <?php echo  $servicio->descripcion; ?>
                     

                  </div>

                

                    <div class="clearfix"> </div>


                </div>

                <br>  
                <hr>  
                <br>  


                  <?php   $i=1; ?>


              <?php }else{ ?>

                 <div class="about-section ">

                  
         
                  <div class="col-md-8 ab-text" style="text-align: left;">
                      <h4 class="tittle"><?php echo  $servicio->titulo; ?></h4>
                      <?php echo  $servicio->descripcion; ?>
                      

                  </div>

                  <div class="col-md-4 ab-left">
                      <div class="grid">
          
                          <img style="" src="<?php echo $this->baseUrl($servicio->imagen); ?>" alt=" " class="">
          
                      </div>
                      <div class="clearfix"> </div>
                  </div>

                

                    <div class="clearfix"> </div>


                </div>

                  <?php   $i=0; ?>

                  <br>  
                <hr>  
                <br> 


              <?php } ?>








               
               <?php endforeach ?>



        <!--//about-section2-->
      </div>
       </div>
      <!--/team-->





